// The commands this frontend emits. The repository-level contract verifier checks
// these values against ui.bridge_contract.ALLOWED_COMMANDS, the canonical allow-list.
export const commands = {
  snapshotGet: 'snapshot.get',
  settingsGet: 'settings.get',
  settingsUpdate: 'settings.update',
  interactionRespond: 'interaction.respond',
  deviceScan: 'device.scan',
  deviceSelect: 'device.select',
  deviceReboot: 'device.reboot',
  deviceSwitchSlot: 'device.switchSlot',
  deviceBootloaderLock: 'device.bootloader.lock',
  deviceBootloaderUnlock: 'device.bootloader.unlock',
  platformToolsSetup: 'platformTools.setup',
  nativePickFile: 'native.pickFile',
  nativePickFiles: 'native.pickFiles',
  nativePickDirectory: 'native.pickDirectory',
  nativeSaveFile: 'native.saveFile',
  firmwareSelect: 'firmware.select',
  firmwareProcess: 'firmware.process',
  flashPlanUpdate: 'flash.plan.update',
  flashPlanPreview: 'flash.plan.preview',
  flashExecute: 'flash.execute',
  bootPatch: 'boot.patch',
  bootFlash: 'boot.flash',
  bootLive: 'boot.live',
  rootAppsList: 'root.apps.list',
  rootAppsInstall: 'root.apps.install',
  rootModulesList: 'root.modules.list',
  rootModulesAction: 'root.modules.action',
  appsList: 'apps.list',
  appsAction: 'apps.action',
  backupsCreate: 'backups.create',
  backupsRestore: 'backups.restore',
  partitionsList: 'partitions.list',
  partitionsRead: 'partitions.read',
  partitionsWrite: 'partitions.write',
  partitionsErase: 'partitions.erase',
  toolsAdbShell: 'tools.adbShell',
  toolsScrcpy: 'tools.scrcpy',
  toolsWifi: 'tools.wifi',
  toolsLogcat: 'tools.logcat',
  toolsPushFiles: 'tools.pushFiles',
  toolsAvb: 'tools.avb',
  supportCreate: 'support.create',
} as const;

export type BridgeCommand = (typeof commands)[keyof typeof commands];
