// @generated by scripts/generate_bridge_contracts.py; DO NOT EDIT.
// Python ui.command_registry.COMMAND_REGISTRY is the canonical source.

export const bridgeVersion = 2 as const;

export const commands = {
  appReady: "app.ready",
  appsAction: "apps.action",
  appsList: "apps.list",
  backupsCreate: "backups.create",
  backupsRestore: "backups.restore",
  bootFlash: "boot.flash",
  bootInventory: "boot.inventory",
  bootLive: "boot.live",
  bootPatch: "boot.patch",
  bootSelect: "boot.select",
  deviceBootloaderLock: "device.bootloader.lock",
  deviceBootloaderUnlock: "device.bootloader.unlock",
  deviceInspect: "device.inspect",
  deviceOtaCertificates: "device.ota.certificates",
  deviceOtaLogs: "device.ota.logs",
  deviceReboot: "device.reboot",
  deviceScan: "device.scan",
  deviceSelect: "device.select",
  deviceSwitchSlot: "device.switchSlot",
  firmwareProcess: "firmware.process",
  firmwareSelect: "firmware.select",
  flashExecute: "flash.execute",
  flashPlanPreview: "flash.plan.preview",
  flashPlanUpdate: "flash.plan.update",
  interactionRespond: "interaction.respond",
  nativePickDirectory: "native.pickDirectory",
  nativePickFile: "native.pickFile",
  nativePickFiles: "native.pickFiles",
  nativeSaveFile: "native.saveFile",
  operationCancel: "operation.cancel",
  partitionsErase: "partitions.erase",
  partitionsList: "partitions.list",
  partitionsRead: "partitions.read",
  partitionsWrite: "partitions.write",
  platformToolsSetup: "platformTools.setup",
  rootAppsInstall: "root.apps.install",
  rootAppsList: "root.apps.list",
  rootModulesAction: "root.modules.action",
  rootModulesList: "root.modules.list",
  secretIssue: "secret.issue",
  settingsGet: "settings.get",
  settingsUpdate: "settings.update",
  snapshotGet: "snapshot.get",
  supportCreate: "support.create",
  toolsLogcat: "tools.logcat",
  toolsLogcatClear: "tools.logcat.clear",
  toolsPushFiles: "tools.pushFiles",
  toolsScrcpy: "tools.scrcpy",
  toolsWifi: "tools.wifi",
  toolsWifiDiscover: "tools.wifi.discover",
  toolsWifiStatus: "tools.wifi.status",
} as const;

export type BridgeCommand = (typeof commands)[keyof typeof commands];

export interface BridgePayloadByCommand {
  "app.ready": Record<string, never>;
  "apps.action": {
    "action": string;
    "grant"?: string;
    "options"?: Record<string, unknown>;
    "package"?: string;
    "packages"?: string[];
    "scope"?: string;
    "serial"?: string;
  };
  "apps.list": {
    "scope"?: string;
    "serial"?: string;
  };
  "backups.create": {
    "grant": string;
    "partition": string;
    "serial"?: string;
    "slot": string;
  };
  "backups.restore": {
    "grant": string;
    "partition": string;
    "serial"?: string;
    "slot": string;
  };
  "boot.flash": {
    "confirmationText"?: string;
    "partition"?: string;
    "serial"?: string;
    "slot"?: string;
  };
  "boot.inventory": Record<string, never>;
  "boot.live": {
    "confirmationText"?: string;
    "serial"?: string;
  };
  "boot.patch": {
    "appId": string;
    "flavor"?: string;
    "grant": string;
    "method"?: string;
    "secretGrant"?: string;
    "serial"?: string;
  };
  "boot.select": {
    "bootId"?: string;
    "grant"?: string;
    "partition"?: string;
  };
  "device.bootloader.lock": {
    "confirmationText"?: string;
    "serial"?: string;
  };
  "device.bootloader.unlock": {
    "confirmationText"?: string;
    "serial"?: string;
  };
  "device.inspect": {
    "action": string;
    "serial"?: string;
  };
  "device.ota.certificates": {
    "serial"?: string;
  };
  "device.ota.logs": {
    "maxLines"?: number;
    "serial"?: string;
    "timeoutSeconds"?: number;
  };
  "device.reboot": {
    "mode"?: string;
    "serial"?: string;
  };
  "device.scan": {
    "includeBattery"?: boolean;
    "includeProperties"?: boolean;
  };
  "device.select": {
    "serials": string[];
  };
  "device.switchSlot": {
    "confirmationText"?: string;
    "serial"?: string;
    "slot": string;
  };
  "firmware.process": Record<string, never>;
  "firmware.select": {
    "firmwareId"?: string;
    "grant"?: string;
  };
  "flash.execute": {
    "confirmationText"?: string;
    "serial"?: string;
  };
  "flash.plan.preview": {
    "serial"?: string;
  };
  "flash.plan.update": {
    "dryRun"?: boolean;
    "mode"?: string;
    "options"?: Record<string, unknown>;
  };
  "interaction.respond": {
    "decision": string;
    "operationId": string;
  };
  "native.pickDirectory": {
    "purpose": string;
    "title"?: string;
  };
  "native.pickFile": {
    "filters"?: Array<{ label: string; extensions: string[] }>;
    "purpose": string;
    "title"?: string;
  };
  "native.pickFiles": {
    "filters"?: Array<{ label: string; extensions: string[] }>;
    "purpose": string;
    "title"?: string;
  };
  "native.saveFile": {
    "defaultName"?: string;
    "filters"?: Array<{ label: string; extensions: string[] }>;
    "purpose": string;
    "title"?: string;
  };
  "operation.cancel": {
    "operationId": string;
  };
  "partitions.erase": {
    "confirmationText"?: string;
    "partition": string;
    "serial"?: string;
  };
  "partitions.list": {
    "serial"?: string;
  };
  "partitions.read": {
    "grant": string;
    "overwrite"?: boolean;
    "partition": string;
    "serial"?: string;
  };
  "partitions.write": {
    "grant": string;
    "partition": string;
    "serial"?: string;
  };
  "platformTools.setup": {
    "grant"?: string;
    "source": string;
  };
  "root.apps.install": {
    "appId": string;
    "serial"?: string;
  };
  "root.apps.list": {
    "serial"?: string;
  };
  "root.modules.action": {
    "action": string;
    "grant"?: string;
    "moduleId"?: string;
    "serial"?: string;
  };
  "root.modules.list": {
    "serial"?: string;
  };
  "secret.issue": {
    "purpose": string;
    "secret": string;
  };
  "settings.get": Record<string, never>;
  "settings.update": {
    "highContrast"?: boolean;
    "locale"?: string;
    "reducedMotion"?: boolean;
    "theme"?: string;
    "zoom"?: number;
  };
  "snapshot.get": Record<string, never>;
  "support.create": {
    "grant": string;
    "includeConfig"?: boolean;
    "includeLogs"?: boolean;
    "includeState"?: boolean;
    "includeSystemInfo"?: boolean;
  };
  "tools.logcat": {
    "buffers"?: string[];
    "filters"?: Array<{ tag: string; priority: "V" | "D" | "I" | "W" | "E" | "F" | "S" }>;
    "formatEnabled"?: boolean;
    "formatModifiers"?: string[];
    "formatVerb"?: string;
    "grant"?: string;
    "maxLines"?: number;
    "mode"?: string;
    "redaction"?: string;
    "regex"?: string;
    "serial"?: string;
    "timeoutSeconds"?: number;
    "uids"?: number[];
  };
  "tools.logcat.clear": {
    "serial"?: string;
  };
  "tools.pushFiles": {
    "destination": string;
    "grants": string[];
    "serial"?: string;
  };
  "tools.scrcpy": {
    "serial"?: string;
  };
  "tools.wifi": {
    "action": string;
    "host": string;
    "port": number;
    "secretGrant"?: string;
  };
  "tools.wifi.discover": Record<string, never>;
  "tools.wifi.status": {
    "serial"?: string;
  };
}

export type BridgeCommandRequest = {
  [Command in BridgeCommand]: {
    command: Command;
    payload: BridgePayloadByCommand[Command];
  };
}[BridgeCommand];

export const allowedCommands = [
  commands.appReady,
  commands.appsAction,
  commands.appsList,
  commands.backupsCreate,
  commands.backupsRestore,
  commands.bootFlash,
  commands.bootInventory,
  commands.bootLive,
  commands.bootPatch,
  commands.bootSelect,
  commands.deviceBootloaderLock,
  commands.deviceBootloaderUnlock,
  commands.deviceInspect,
  commands.deviceOtaCertificates,
  commands.deviceOtaLogs,
  commands.deviceReboot,
  commands.deviceScan,
  commands.deviceSelect,
  commands.deviceSwitchSlot,
  commands.firmwareProcess,
  commands.firmwareSelect,
  commands.flashExecute,
  commands.flashPlanPreview,
  commands.flashPlanUpdate,
  commands.interactionRespond,
  commands.nativePickDirectory,
  commands.nativePickFile,
  commands.nativePickFiles,
  commands.nativeSaveFile,
  commands.operationCancel,
  commands.partitionsErase,
  commands.partitionsList,
  commands.partitionsRead,
  commands.partitionsWrite,
  commands.platformToolsSetup,
  commands.rootAppsInstall,
  commands.rootAppsList,
  commands.rootModulesAction,
  commands.rootModulesList,
  commands.secretIssue,
  commands.settingsGet,
  commands.settingsUpdate,
  commands.snapshotGet,
  commands.supportCreate,
  commands.toolsLogcat,
  commands.toolsLogcatClear,
  commands.toolsPushFiles,
  commands.toolsScrcpy,
  commands.toolsWifi,
  commands.toolsWifiDiscover,
  commands.toolsWifiStatus,
] as const;

export const revisionOptionalCommands = new Set<BridgeCommand>([
  commands.appReady,
  commands.settingsGet,
  commands.snapshotGet,
]);

export const commandTimeoutByName: Readonly<Record<BridgeCommand, number>> = {
  [commands.appReady]: 60000,
  [commands.appsAction]: 1200000,
  [commands.appsList]: 300000,
  [commands.backupsCreate]: 1800000,
  [commands.backupsRestore]: 1800000,
  [commands.bootFlash]: 1200000,
  [commands.bootInventory]: 21600000,
  [commands.bootLive]: 600000,
  [commands.bootPatch]: 10800000,
  [commands.bootSelect]: 5400000,
  [commands.deviceBootloaderLock]: 600000,
  [commands.deviceBootloaderUnlock]: 600000,
  [commands.deviceInspect]: 45000,
  [commands.deviceOtaCertificates]: 45000,
  [commands.deviceOtaLogs]: 180000,
  [commands.deviceReboot]: 600000,
  [commands.deviceScan]: 600000,
  [commands.deviceSelect]: 60000,
  [commands.deviceSwitchSlot]: 600000,
  [commands.firmwareProcess]: 7200000,
  [commands.firmwareSelect]: 3600000,
  [commands.flashExecute]: 14400000,
  [commands.flashPlanPreview]: 60000,
  [commands.flashPlanUpdate]: 60000,
  [commands.interactionRespond]: 60000,
  [commands.nativePickDirectory]: 60000,
  [commands.nativePickFile]: 60000,
  [commands.nativePickFiles]: 60000,
  [commands.nativeSaveFile]: 60000,
  [commands.operationCancel]: 60000,
  [commands.partitionsErase]: 600000,
  [commands.partitionsList]: 60000,
  [commands.partitionsRead]: 1200000,
  [commands.partitionsWrite]: 1200000,
  [commands.platformToolsSetup]: 1800000,
  [commands.rootAppsInstall]: 1800000,
  [commands.rootAppsList]: 3600000,
  [commands.rootModulesAction]: 1800000,
  [commands.rootModulesList]: 300000,
  [commands.secretIssue]: 60000,
  [commands.settingsGet]: 60000,
  [commands.settingsUpdate]: 60000,
  [commands.snapshotGet]: 60000,
  [commands.supportCreate]: 1800000,
  [commands.toolsLogcat]: 180000,
  [commands.toolsLogcatClear]: 180000,
  [commands.toolsPushFiles]: 21600000,
  [commands.toolsScrcpy]: 300000,
  [commands.toolsWifi]: 300000,
  [commands.toolsWifiDiscover]: 20000,
  [commands.toolsWifiStatus]: 60000,
};

export const bridgeCommandMetadata = {
  [commands.appReady]: {"owner":"application","mutability":"read_only","risk":"none","expectedRevision":"optional","validDeviceStates":["*"],"planner":"native_host.lifecycle","confirmation":"none","postconditions":["snapshot_emitted"]},
  [commands.appsAction]: {"owner":"applications","mutability":"mutating","risk":"device_write","expectedRevision":"required","validDeviceStates":["adb","recovery","sideload"],"planner":"apps.action","confirmation":"standard","postconditions":["package_state_verified"]},
  [commands.appsList]: {"owner":"applications","mutability":"read_only","risk":"device_read","expectedRevision":"required","validDeviceStates":["adb","recovery","sideload"],"planner":"apps.inventory","confirmation":"none","postconditions":["packages_returned"]},
  [commands.backupsCreate]: {"owner":"backups","mutability":"mutating","risk":"host_write","expectedRevision":"required","validDeviceStates":["adb","fastboot","fastbootd","recovery","sideload"],"planner":"backups.create","confirmation":"none","postconditions":["backup_hash_verified"]},
  [commands.backupsRestore]: {"owner":"backups","mutability":"mutating","risk":"device_write","expectedRevision":"required","validDeviceStates":["adb","fastboot","fastbootd","recovery","sideload"],"planner":"backups.restore","confirmation":"standard","postconditions":["restore_write_verified"]},
  [commands.bootFlash]: {"owner":"boot_images","mutability":"destructive","risk":"destructive","expectedRevision":"required","validDeviceStates":["fastboot","fastbootd"],"planner":"operation.boot_flash","confirmation":"standard","postconditions":["partition_write_verified"]},
  [commands.bootInventory]: {"owner":"boot_images","mutability":"read_only","risk":"host_read","expectedRevision":"required","validDeviceStates":["*"],"planner":"boot_inventory.list","confirmation":"none","postconditions":["boot_metadata_returned"]},
  [commands.bootLive]: {"owner":"boot_images","mutability":"mutating","risk":"device_write","expectedRevision":"required","validDeviceStates":["fastboot","fastbootd"],"planner":"operation.boot_live","confirmation":"standard","postconditions":["device_reconnected","boot_completed_observed"]},
  [commands.bootPatch]: {"owner":"boot_images","mutability":"mutating","risk":"host_write","expectedRevision":"required","validDeviceStates":["adb","recovery","sideload"],"planner":"boot.patch","confirmation":"standard","postconditions":["patched_artifact_hashed","boot_repository_updated"]},
  [commands.bootSelect]: {"owner":"boot_images","mutability":"mutating","risk":"host_write","expectedRevision":"required","validDeviceStates":["*"],"planner":"boot_inventory.select","confirmation":"none","postconditions":["boot_repository_verified","boot_snapshot_matches"]},
  [commands.deviceBootloaderLock]: {"owner":"bootloader","mutability":"destructive","risk":"destructive","expectedRevision":"required","validDeviceStates":["fastboot","fastbootd"],"planner":"operation.bootloader_lock","confirmation":"lock_serial","postconditions":["bootloader_locked","relock_evidence_consumed"]},
  [commands.deviceBootloaderUnlock]: {"owner":"bootloader","mutability":"destructive","risk":"destructive","expectedRevision":"required","validDeviceStates":["fastboot","fastbootd"],"planner":"operation.bootloader_unlock","confirmation":"unlock_serial","postconditions":["bootloader_unlocked"]},
  [commands.deviceInspect]: {"owner":"device_tools","mutability":"read_only","risk":"device_read","expectedRevision":"required","validDeviceStates":["adb"],"planner":"device.inspect","confirmation":"none","postconditions":["bounded_typed_report_returned"]},
  [commands.deviceOtaCertificates]: {"owner":"device_tools","mutability":"read_only","risk":"device_read","expectedRevision":"required","validDeviceStates":["adb"],"planner":"device.ota.certificates","confirmation":"none","postconditions":["bounded_certificate_inventory_returned"]},
  [commands.deviceOtaLogs]: {"owner":"device_tools","mutability":"read_only","risk":"device_read","expectedRevision":"required","validDeviceStates":["adb"],"planner":"device.ota.logs","confirmation":"none","postconditions":["bounded_redacted_logs_returned"]},
  [commands.deviceReboot]: {"owner":"device","mutability":"mutating","risk":"device_write","expectedRevision":"required","validDeviceStates":["adb","fastboot","fastbootd","recovery","sideload"],"planner":"operation.device_reboot","confirmation":"none","postconditions":["device_reconnected","expected_mode_observed"]},
  [commands.deviceScan]: {"owner":"device","mutability":"read_only","risk":"device_read","expectedRevision":"required","validDeviceStates":["*"],"planner":"device.scan","confirmation":"none","postconditions":["device_inventory_refreshed"]},
  [commands.deviceSelect]: {"owner":"device","mutability":"mutating","risk":"none","expectedRevision":"required","validDeviceStates":["*"],"planner":"device.selection","confirmation":"none","postconditions":["selected_serials_match"]},
  [commands.deviceSwitchSlot]: {"owner":"device","mutability":"destructive","risk":"destructive","expectedRevision":"required","validDeviceStates":["fastboot","fastbootd"],"planner":"operation.slot_switch","confirmation":"slot_serial","postconditions":["active_slot_matches"]},
  [commands.firmwareProcess]: {"owner":"firmware","mutability":"mutating","risk":"host_write","expectedRevision":"required","validDeviceStates":["*"],"planner":"firmware.process","confirmation":"none","postconditions":["artifacts_hashed","firmware_repository_updated"]},
  [commands.firmwareSelect]: {"owner":"firmware","mutability":"mutating","risk":"host_read","expectedRevision":"required","validDeviceStates":["*"],"planner":"firmware.inspect","confirmation":"none","postconditions":["firmware_snapshot_matches"]},
  [commands.flashExecute]: {"owner":"flash","mutability":"destructive","risk":"destructive","expectedRevision":"required","validDeviceStates":["adb","fastboot","fastbootd","recovery","sideload"],"planner":"operation.flash","confirmation":"plan_fingerprint","postconditions":["device_reconnected","build_matches","slot_matches"]},
  [commands.flashPlanPreview]: {"owner":"flash","mutability":"read_only","risk":"device_read","expectedRevision":"required","validDeviceStates":["adb","fastboot","fastbootd","recovery","sideload"],"planner":"flash.preview","confirmation":"none","postconditions":["immutable_plan_returned"]},
  [commands.flashPlanUpdate]: {"owner":"flash","mutability":"mutating","risk":"none","expectedRevision":"required","validDeviceStates":["*"],"planner":"flash.intent","confirmation":"none","postconditions":["flash_intent_snapshot_matches"]},
  [commands.interactionRespond]: {"owner":"application","mutability":"mutating","risk":"none","expectedRevision":"required","validDeviceStates":["*"],"planner":"engine.interaction","confirmation":"none","postconditions":["interaction_acknowledged"]},
  [commands.nativePickDirectory]: {"owner":"native_host","mutability":"read_only","risk":"host_read","expectedRevision":"required","validDeviceStates":["*"],"planner":"native_host.pick_directory","confirmation":"none","postconditions":["path_grant_issued"]},
  [commands.nativePickFile]: {"owner":"native_host","mutability":"read_only","risk":"host_read","expectedRevision":"required","validDeviceStates":["*"],"planner":"native_host.pick_file","confirmation":"none","postconditions":["path_grant_issued"]},
  [commands.nativePickFiles]: {"owner":"native_host","mutability":"read_only","risk":"host_read","expectedRevision":"required","validDeviceStates":["*"],"planner":"native_host.pick_files","confirmation":"none","postconditions":["path_grants_issued"]},
  [commands.nativeSaveFile]: {"owner":"native_host","mutability":"read_only","risk":"host_write","expectedRevision":"required","validDeviceStates":["*"],"planner":"native_host.save_file","confirmation":"none","postconditions":["write_grant_issued"]},
  [commands.operationCancel]: {"owner":"application","mutability":"mutating","risk":"none","expectedRevision":"required","validDeviceStates":["*"],"planner":"engine.cancellation","confirmation":"none","postconditions":["cancellation_acknowledged"]},
  [commands.partitionsErase]: {"owner":"partitions","mutability":"destructive","risk":"destructive","expectedRevision":"required","validDeviceStates":["fastboot","fastbootd"],"planner":"partitions.erase","confirmation":"erase_partition_serial","postconditions":["partition_erased_verified"]},
  [commands.partitionsList]: {"owner":"partitions","mutability":"read_only","risk":"device_read","expectedRevision":"required","validDeviceStates":["fastboot","fastbootd"],"planner":"partitions.inventory","confirmation":"none","postconditions":["partition_inventory_returned"]},
  [commands.partitionsRead]: {"owner":"partitions","mutability":"mutating","risk":"host_write","expectedRevision":"required","validDeviceStates":["fastboot","fastbootd"],"planner":"partitions.read","confirmation":"none","postconditions":["local_hash_verified"]},
  [commands.partitionsWrite]: {"owner":"partitions","mutability":"destructive","risk":"destructive","expectedRevision":"required","validDeviceStates":["fastboot","fastbootd"],"planner":"partitions.write","confirmation":"standard","postconditions":["partition_write_verified"]},
  [commands.platformToolsSetup]: {"owner":"platform_tools","mutability":"mutating","risk":"host_write","expectedRevision":"required","validDeviceStates":["*"],"planner":"toolchain.setup","confirmation":"none","postconditions":["adb_fastboot_probed"]},
  [commands.rootAppsInstall]: {"owner":"root","mutability":"mutating","risk":"device_write","expectedRevision":"required","validDeviceStates":["adb","recovery","sideload"],"planner":"root.app_install","confirmation":"standard","postconditions":["package_installed"]},
  [commands.rootAppsList]: {"owner":"root","mutability":"read_only","risk":"host_read","expectedRevision":"required","validDeviceStates":["*"],"planner":"root.apps_inventory","confirmation":"none","postconditions":["root_apps_returned"]},
  [commands.rootModulesAction]: {"owner":"root","mutability":"destructive","risk":"destructive","expectedRevision":"required","validDeviceStates":["adb","recovery","sideload"],"planner":"root.module_action","confirmation":"standard","postconditions":["root_module_state_verified"]},
  [commands.rootModulesList]: {"owner":"root","mutability":"read_only","risk":"device_read","expectedRevision":"required","validDeviceStates":["adb","recovery","sideload"],"planner":"root.modules_inventory","confirmation":"none","postconditions":["root_modules_returned"]},
  [commands.secretIssue]: {"owner":"native_host","mutability":"mutating","risk":"none","expectedRevision":"required","validDeviceStates":["*"],"planner":"native_host.secret_grant","confirmation":"none","postconditions":["secret_grant_issued"]},
  [commands.settingsGet]: {"owner":"settings","mutability":"read_only","risk":"host_read","expectedRevision":"optional","validDeviceStates":["*"],"planner":"runtime.settings_get","confirmation":"none","postconditions":["preferences_returned"]},
  [commands.settingsUpdate]: {"owner":"settings","mutability":"mutating","risk":"host_write","expectedRevision":"required","validDeviceStates":["*"],"planner":"runtime.settings_update","confirmation":"none","postconditions":["preferences_persisted"]},
  [commands.snapshotGet]: {"owner":"application","mutability":"read_only","risk":"none","expectedRevision":"optional","validDeviceStates":["*"],"planner":"engine.snapshot","confirmation":"none","postconditions":["snapshot_returned"]},
  [commands.supportCreate]: {"owner":"support","mutability":"mutating","risk":"host_write","expectedRevision":"required","validDeviceStates":["*"],"planner":"support.package_v2","confirmation":"none","postconditions":["encrypted_container_verified"]},
  [commands.toolsLogcat]: {"owner":"device_tools","mutability":"mutating","risk":"host_write","expectedRevision":"required","validDeviceStates":["adb"],"planner":"tools.logcat","confirmation":"none","postconditions":["bounded_log_returned"]},
  [commands.toolsLogcatClear]: {"owner":"device_tools","mutability":"destructive","risk":"destructive","expectedRevision":"required","validDeviceStates":["adb"],"planner":"tools.logcat.clear","confirmation":"standard","postconditions":["logcat_buffers_cleared"]},
  [commands.toolsPushFiles]: {"owner":"device_tools","mutability":"mutating","risk":"device_write","expectedRevision":"required","validDeviceStates":["adb"],"planner":"tools.push_files","confirmation":"standard","postconditions":["remote_files_written"]},
  [commands.toolsScrcpy]: {"owner":"device_tools","mutability":"read_only","risk":"device_read","expectedRevision":"required","validDeviceStates":["adb"],"planner":"tools.scrcpy","confirmation":"none","postconditions":["managed_process_started"]},
  [commands.toolsWifi]: {"owner":"device_tools","mutability":"mutating","risk":"host_write","expectedRevision":"required","validDeviceStates":["*"],"planner":"tools.wifi","confirmation":"none","postconditions":["adb_endpoint_observed"]},
  [commands.toolsWifiDiscover]: {"owner":"device_tools","mutability":"read_only","risk":"host_read","expectedRevision":"required","validDeviceStates":["*"],"planner":"tools.wifi.discover","confirmation":"none","postconditions":[]},
  [commands.toolsWifiStatus]: {"owner":"device_tools","mutability":"read_only","risk":"device_read","expectedRevision":"required","validDeviceStates":["adb"],"planner":"tools.wifi.status","confirmation":"none","postconditions":["adb_device_state_returned"]},
} as const satisfies Readonly<Record<BridgeCommand, {
  owner: string;
  mutability: string;
  risk: string;
  expectedRevision: 'optional' | 'required';
  validDeviceStates: readonly string[];
  planner: string;
  confirmation: string;
  postconditions: readonly string[];
}>>;

type GeneratedPayloadKind =
  | 'string'
  | 'boolean'
  | 'integer'
  | 'number'
  | 'object'
  | 'array'
  | 'string_array'
  | 'integer_array'
  | 'logcat_filter_array'
  | 'filter_array';

interface GeneratedPayloadField {
  readonly kind: GeneratedPayloadKind;
  readonly required: boolean;
  readonly minItems?: number;
  readonly maxItems?: number;
}

export const bridgePayloadSchemas: Readonly<Record<
  BridgeCommand,
  Readonly<Record<string, GeneratedPayloadField>>
>> = {
  [commands.appReady]: {},
  [commands.appsAction]: {"action":{"kind":"string","required":true},"grant":{"kind":"string","required":false},"options":{"kind":"object","required":false},"package":{"kind":"string","required":false},"packages":{"kind":"string_array","required":false},"scope":{"kind":"string","required":false},"serial":{"kind":"string","required":false}},
  [commands.appsList]: {"scope":{"kind":"string","required":false},"serial":{"kind":"string","required":false}},
  [commands.backupsCreate]: {"grant":{"kind":"string","required":true},"partition":{"kind":"string","required":true},"serial":{"kind":"string","required":false},"slot":{"kind":"string","required":true}},
  [commands.backupsRestore]: {"grant":{"kind":"string","required":true},"partition":{"kind":"string","required":true},"serial":{"kind":"string","required":false},"slot":{"kind":"string","required":true}},
  [commands.bootFlash]: {"confirmationText":{"kind":"string","required":false},"partition":{"kind":"string","required":false},"serial":{"kind":"string","required":false},"slot":{"kind":"string","required":false}},
  [commands.bootInventory]: {},
  [commands.bootLive]: {"confirmationText":{"kind":"string","required":false},"serial":{"kind":"string","required":false}},
  [commands.bootPatch]: {"appId":{"kind":"string","required":true},"flavor":{"kind":"string","required":false},"grant":{"kind":"string","required":true},"method":{"kind":"string","required":false},"secretGrant":{"kind":"string","required":false},"serial":{"kind":"string","required":false}},
  [commands.bootSelect]: {"bootId":{"kind":"string","required":false},"grant":{"kind":"string","required":false},"partition":{"kind":"string","required":false}},
  [commands.deviceBootloaderLock]: {"confirmationText":{"kind":"string","required":false},"serial":{"kind":"string","required":false}},
  [commands.deviceBootloaderUnlock]: {"confirmationText":{"kind":"string","required":false},"serial":{"kind":"string","required":false}},
  [commands.deviceInspect]: {"action":{"kind":"string","required":true},"serial":{"kind":"string","required":false}},
  [commands.deviceOtaCertificates]: {"serial":{"kind":"string","required":false}},
  [commands.deviceOtaLogs]: {"maxLines":{"kind":"integer","required":false},"serial":{"kind":"string","required":false},"timeoutSeconds":{"kind":"integer","required":false}},
  [commands.deviceReboot]: {"mode":{"kind":"string","required":false},"serial":{"kind":"string","required":false}},
  [commands.deviceScan]: {"includeBattery":{"kind":"boolean","required":false},"includeProperties":{"kind":"boolean","required":false}},
  [commands.deviceSelect]: {"serials":{"kind":"string_array","required":true}},
  [commands.deviceSwitchSlot]: {"confirmationText":{"kind":"string","required":false},"serial":{"kind":"string","required":false},"slot":{"kind":"string","required":true}},
  [commands.firmwareProcess]: {},
  [commands.firmwareSelect]: {"firmwareId":{"kind":"string","required":false},"grant":{"kind":"string","required":false}},
  [commands.flashExecute]: {"confirmationText":{"kind":"string","required":false},"serial":{"kind":"string","required":false}},
  [commands.flashPlanPreview]: {"serial":{"kind":"string","required":false}},
  [commands.flashPlanUpdate]: {"dryRun":{"kind":"boolean","required":false},"mode":{"kind":"string","required":false},"options":{"kind":"object","required":false}},
  [commands.interactionRespond]: {"decision":{"kind":"string","required":true},"operationId":{"kind":"string","required":true}},
  [commands.nativePickDirectory]: {"purpose":{"kind":"string","required":true},"title":{"kind":"string","required":false}},
  [commands.nativePickFile]: {"filters":{"kind":"filter_array","required":false},"purpose":{"kind":"string","required":true},"title":{"kind":"string","required":false}},
  [commands.nativePickFiles]: {"filters":{"kind":"filter_array","required":false},"purpose":{"kind":"string","required":true},"title":{"kind":"string","required":false}},
  [commands.nativeSaveFile]: {"defaultName":{"kind":"string","required":false},"filters":{"kind":"filter_array","required":false},"purpose":{"kind":"string","required":true},"title":{"kind":"string","required":false}},
  [commands.operationCancel]: {"operationId":{"kind":"string","required":true}},
  [commands.partitionsErase]: {"confirmationText":{"kind":"string","required":false},"partition":{"kind":"string","required":true},"serial":{"kind":"string","required":false}},
  [commands.partitionsList]: {"serial":{"kind":"string","required":false}},
  [commands.partitionsRead]: {"grant":{"kind":"string","required":true},"overwrite":{"kind":"boolean","required":false},"partition":{"kind":"string","required":true},"serial":{"kind":"string","required":false}},
  [commands.partitionsWrite]: {"grant":{"kind":"string","required":true},"partition":{"kind":"string","required":true},"serial":{"kind":"string","required":false}},
  [commands.platformToolsSetup]: {"grant":{"kind":"string","required":false},"source":{"kind":"string","required":true}},
  [commands.rootAppsInstall]: {"appId":{"kind":"string","required":true},"serial":{"kind":"string","required":false}},
  [commands.rootAppsList]: {"serial":{"kind":"string","required":false}},
  [commands.rootModulesAction]: {"action":{"kind":"string","required":true},"grant":{"kind":"string","required":false},"moduleId":{"kind":"string","required":false},"serial":{"kind":"string","required":false}},
  [commands.rootModulesList]: {"serial":{"kind":"string","required":false}},
  [commands.secretIssue]: {"purpose":{"kind":"string","required":true},"secret":{"kind":"string","required":true}},
  [commands.settingsGet]: {},
  [commands.settingsUpdate]: {"highContrast":{"kind":"boolean","required":false},"locale":{"kind":"string","required":false},"reducedMotion":{"kind":"boolean","required":false},"theme":{"kind":"string","required":false},"zoom":{"kind":"integer","required":false}},
  [commands.snapshotGet]: {},
  [commands.supportCreate]: {"grant":{"kind":"string","required":true},"includeConfig":{"kind":"boolean","required":false},"includeLogs":{"kind":"boolean","required":false},"includeState":{"kind":"boolean","required":false},"includeSystemInfo":{"kind":"boolean","required":false}},
  [commands.toolsLogcat]: {"buffers":{"kind":"string_array","required":false,"minItems":1,"maxItems":6},"filters":{"kind":"logcat_filter_array","required":false,"minItems":0,"maxItems":32},"formatEnabled":{"kind":"boolean","required":false},"formatModifiers":{"kind":"string_array","required":false,"minItems":0,"maxItems":7},"formatVerb":{"kind":"string","required":false},"grant":{"kind":"string","required":false},"maxLines":{"kind":"integer","required":false},"mode":{"kind":"string","required":false},"redaction":{"kind":"string","required":false},"regex":{"kind":"string","required":false},"serial":{"kind":"string","required":false},"timeoutSeconds":{"kind":"integer","required":false},"uids":{"kind":"integer_array","required":false,"minItems":0,"maxItems":32}},
  [commands.toolsLogcatClear]: {"serial":{"kind":"string","required":false}},
  [commands.toolsPushFiles]: {"destination":{"kind":"string","required":true},"grants":{"kind":"string_array","required":true,"minItems":1,"maxItems":32},"serial":{"kind":"string","required":false}},
  [commands.toolsScrcpy]: {"serial":{"kind":"string","required":false}},
  [commands.toolsWifi]: {"action":{"kind":"string","required":true},"host":{"kind":"string","required":true},"port":{"kind":"integer","required":true},"secretGrant":{"kind":"string","required":false}},
  [commands.toolsWifiDiscover]: {},
  [commands.toolsWifiStatus]: {"serial":{"kind":"string","required":false}},
};

const commandSet = new Set<string>(allowedCommands);

export function isBridgeCommand(value: unknown): value is BridgeCommand {
  return typeof value === 'string' && commandSet.has(value);
}

function matchesPayloadKind(value: unknown, kind: GeneratedPayloadKind): boolean {
  switch (kind) {
    case 'string': return typeof value === 'string';
    case 'boolean': return typeof value === 'boolean';
    case 'integer': return typeof value === 'number' && Number.isInteger(value);
    case 'number': return typeof value === 'number' && Number.isFinite(value);
    case 'object': return value !== null && typeof value === 'object' && !Array.isArray(value);
    case 'array': return Array.isArray(value);
    case 'integer_array': return Array.isArray(value) && value.every((item) => Number.isSafeInteger(item));
    case 'logcat_filter_array': return Array.isArray(value) && value.every((item) => {
      if (item === null || typeof item !== 'object' || Array.isArray(item)) return false;
      const filter = item as Record<string, unknown>;
      const keys = Object.keys(filter).sort();
      return keys.length === 2 && keys[0] === 'priority' && keys[1] === 'tag'
        && typeof filter.tag === 'string' && typeof filter.priority === 'string';
    });
    case 'filter_array': return Array.isArray(value) && value.every((item) => {
      if (item === null || typeof item !== 'object' || Array.isArray(item)) return false;
      const filter = item as Record<string, unknown>;
      if (Object.keys(filter).length !== 2 || typeof filter.label !== 'string') return false;
      return Array.isArray(filter.extensions) && filter.extensions.every((entry) => typeof entry === 'string');
    });
    case 'string_array': return Array.isArray(value) && value.every((item) => typeof item === 'string');
  }
}

export function isBridgePayload<Command extends BridgeCommand>(
  command: Command,
  payload: unknown,
): payload is BridgePayloadByCommand[Command] {
  if (payload === null || typeof payload !== 'object' || Array.isArray(payload)) return false;
  const schema = bridgePayloadSchemas[command];
  const values = payload as Record<string, unknown>;
  for (const key of Object.keys(values)) {
    if (!Object.prototype.hasOwnProperty.call(schema, key)) return false;
  }
  for (const [key, field] of Object.entries(schema)) {
    if (!Object.prototype.hasOwnProperty.call(values, key)) {
      if (field.required) return false;
      continue;
    }
    if (!matchesPayloadKind(values[key], field.kind)) return false;
    if (Array.isArray(values[key]) && field.minItems !== undefined && (
      values[key].length < field.minItems
      || values[key].length > (field.maxItems ?? field.minItems)
    )) return false;
  }
  return true;
}
