// @generated by scripts/generate_bridge_contracts.py; DO NOT EDIT.
// Python ui.command_registry.COMMAND_REGISTRY is the canonical source.

export const bridgeVersion = 2 as const;

export const commands = {
  appConsoleExport: "app.console.export",
  appExit: "app.exit",
  appOpenFolder: "app.openFolder",
  appOpenLink: "app.openLink",
  appReady: "app.ready",
  appsAction: "apps.action",
  appsList: "apps.list",
  backupsCreate: "backups.create",
  backupsDelete: "backups.delete",
  backupsList: "backups.list",
  backupsMagiskDelete: "backups.magisk.delete",
  backupsMagiskImport: "backups.magisk.import",
  backupsMagiskList: "backups.magisk.list",
  backupsRestore: "backups.restore",
  bootDelete: "boot.delete",
  bootFlash: "boot.flash",
  bootInventory: "boot.inventory",
  bootLive: "boot.live",
  bootPatch: "boot.patch",
  bootSelect: "boot.select",
  deviceBootloaderLock: "device.bootloader.lock",
  deviceBootloaderUnlock: "device.bootloader.unlock",
  deviceInspect: "device.inspect",
  deviceManagerPolicy: "device.manager.policy",
  deviceManagerRemove: "device.manager.remove",
  deviceManagerUpdate: "device.manager.update",
  deviceOpenUrl: "device.openUrl",
  deviceOtaCertificates: "device.ota.certificates",
  deviceOtaLogs: "device.ota.logs",
  deviceOtaReset: "device.ota.reset",
  deviceOtaStatus: "device.ota.status",
  deviceReboot: "device.reboot",
  deviceScan: "device.scan",
  deviceSelect: "device.select",
  deviceSwitchSlot: "device.switchSlot",
  firmwareCatalogRefresh: "firmware.catalog.refresh",
  firmwareDownload: "firmware.download",
  firmwareProcess: "firmware.process",
  firmwareSelect: "firmware.select",
  flashExecute: "flash.execute",
  flashPlanPreview: "flash.plan.preview",
  flashPlanUpdate: "flash.plan.update",
  interactionRespond: "interaction.respond",
  nativePickDirectory: "native.pickDirectory",
  nativePickFile: "native.pickFile",
  nativePickFiles: "native.pickFiles",
  nativeSaveFile: "native.saveFile",
  operationCancel: "operation.cancel",
  partitionsErase: "partitions.erase",
  partitionsList: "partitions.list",
  partitionsRead: "partitions.read",
  partitionsWrite: "partitions.write",
  platformToolsSetup: "platformTools.setup",
  rootAppsCatalogRefresh: "root.apps.catalog.refresh",
  rootAppsDownload: "root.apps.download",
  rootAppsInstall: "root.apps.install",
  rootAppsList: "root.apps.list",
  rootDataAdbBackup: "root.dataAdb.backup",
  rootDataAdbClear: "root.dataAdb.clear",
  rootDataAdbRestore: "root.dataAdb.restore",
  rootModulesAction: "root.modules.action",
  rootModulesList: "root.modules.list",
  rootModulesUpdates: "root.modules.updates",
  rootPifDocument: "root.pif.document",
  rootPifFavoritesDelete: "root.pif.favorites.delete",
  rootPifFavoritesGet: "root.pif.favorites.get",
  rootPifFavoritesList: "root.pif.favorites.list",
  rootPifFavoritesSave: "root.pif.favorites.save",
  rootPifInventory: "root.pif.inventory",
  rootPifTransform: "root.pif.transform",
  secretIssue: "secret.issue",
  settingsGet: "settings.get",
  settingsUpdate: "settings.update",
  snapshotGet: "snapshot.get",
  supportCreate: "support.create",
  toolsAdbShell: "tools.adbShell",
  toolsAdbShellClose: "tools.adbShell.close",
  toolsAdbShellResize: "tools.adbShell.resize",
  toolsAdbShellWrite: "tools.adbShell.write",
  toolsAvb: "tools.avb",
  toolsKeybox: "tools.keybox",
  toolsLogcat: "tools.logcat",
  toolsLogcatClear: "tools.logcat.clear",
  toolsMyTools: "tools.myTools",
  toolsPiAnalysis: "tools.piAnalysis",
  toolsPif: "tools.pif",
  toolsPushFiles: "tools.pushFiles",
  toolsScrcpy: "tools.scrcpy",
  toolsScrcpySetup: "tools.scrcpy.setup",
  toolsShizuku: "tools.shizuku",
  toolsSos: "tools.sos",
  toolsWifi: "tools.wifi",
  toolsWifiDiscover: "tools.wifi.discover",
  toolsWifiStatus: "tools.wifi.status",
  toolsXml: "tools.xml",
  updatesCheck: "updates.check",
} as const;

export type BridgeCommand = (typeof commands)[keyof typeof commands];

export interface BridgePayloadByCommand {
  "app.console.export": {
    "grant": string;
    "lines": string[];
  };
  "app.exit": Record<string, never>;
  "app.openFolder": {
    "target": string;
  };
  "app.openLink": {
    "target": string;
  };
  "app.ready": Record<string, never>;
  "apps.action": {
    "action": string;
    "grant"?: string;
    "options"?: Record<string, unknown>;
    "package"?: string;
    "packages"?: string[];
    "scope"?: string;
    "serial"?: string;
  };
  "apps.list": {
    "scope"?: string;
    "serial"?: string;
  };
  "backups.create": {
    "grant": string;
    "partition": string;
    "serial"?: string;
    "slot": string;
  };
  "backups.delete": {
    "backupId": string;
    "confirmationText": string;
  };
  "backups.list": {
    "serial"?: string;
  };
  "backups.magisk.delete": {
    "confirmationText": string;
    "serial": string;
    "sha1": string;
  };
  "backups.magisk.import": {
    "grant": string;
    "serial": string;
  };
  "backups.magisk.list": {
    "serial": string;
  };
  "backups.restore": {
    "backupId"?: string;
    "grant"?: string;
    "partition": string;
    "serial"?: string;
    "slot": string;
  };
  "boot.delete": {
    "bootId": string;
  };
  "boot.flash": {
    "confirmationText"?: string;
    "partition"?: string;
    "serial"?: string;
    "slot"?: string;
  };
  "boot.inventory": Record<string, never>;
  "boot.live": {
    "confirmationText"?: string;
    "serial"?: string;
  };
  "boot.patch": {
    "appId": string;
    "flavor"?: string;
    "grant": string;
    "method"?: string;
    "secretGrant"?: string;
    "serial"?: string;
  };
  "boot.select": {
    "bootId"?: string;
    "grant"?: string;
    "partition"?: string;
  };
  "device.bootloader.lock": {
    "confirmationText"?: string;
    "serial"?: string;
  };
  "device.bootloader.unlock": {
    "confirmationText"?: string;
    "serial"?: string;
  };
  "device.inspect": {
    "action": string;
    "serial"?: string;
  };
  "device.manager.policy": {
    "scanEnabled"?: boolean;
    "scanScope"?: string;
  };
  "device.manager.remove": {
    "serial": string;
  };
  "device.manager.update": {
    "enabled"?: boolean;
    "label"?: string;
    "serial": string;
  };
  "device.openUrl": {
    "serial"?: string;
    "url": string;
  };
  "device.ota.certificates": {
    "serial"?: string;
  };
  "device.ota.logs": {
    "maxLines"?: number;
    "serial"?: string;
    "timeoutSeconds"?: number;
  };
  "device.ota.reset": {
    "serial"?: string;
  };
  "device.ota.status": {
    "serial"?: string;
  };
  "device.reboot": {
    "mode"?: string;
    "serial"?: string;
  };
  "device.scan": {
    "includeBattery"?: boolean;
    "includeProperties"?: boolean;
  };
  "device.select": {
    "serials": string[];
  };
  "device.switchSlot": {
    "confirmationText"?: string;
    "serial"?: string;
    "slot": string;
  };
  "firmware.catalog.refresh": {
    "channel"?: string;
    "device"?: string;
  };
  "firmware.download": {
    "artifactId": string;
  };
  "firmware.process": Record<string, never>;
  "firmware.select": {
    "expectedKind"?: string;
    "firmwareId"?: string;
    "grant"?: string;
  };
  "flash.execute": {
    "confirmationText"?: string;
    "serial"?: string;
  };
  "flash.plan.preview": {
    "serial"?: string;
  };
  "flash.plan.update": {
    "dryRun"?: boolean;
    "mode"?: string;
    "options"?: Record<string, unknown>;
  };
  "interaction.respond": {
    "decision": string;
    "operationId": string;
  };
  "native.pickDirectory": {
    "purpose": string;
    "title"?: string;
  };
  "native.pickFile": {
    "filters"?: Array<{ label: string; extensions: string[] }>;
    "purpose": string;
    "title"?: string;
  };
  "native.pickFiles": {
    "filters"?: Array<{ label: string; extensions: string[] }>;
    "purpose": string;
    "title"?: string;
  };
  "native.saveFile": {
    "defaultName"?: string;
    "filters"?: Array<{ label: string; extensions: string[] }>;
    "purpose": string;
    "title"?: string;
  };
  "operation.cancel": {
    "operationId": string;
  };
  "partitions.erase": {
    "confirmationText"?: string;
    "partition": string;
    "serial"?: string;
  };
  "partitions.list": {
    "serial"?: string;
  };
  "partitions.read": {
    "grant": string;
    "overwrite"?: boolean;
    "partition": string;
    "serial"?: string;
  };
  "partitions.write": {
    "grant": string;
    "partition": string;
    "serial"?: string;
  };
  "platformTools.setup": {
    "grant"?: string;
    "source": string;
  };
  "root.apps.catalog.refresh": {
    "channel"?: string;
  };
  "root.apps.download": {
    "artifactId": string;
  };
  "root.apps.install": {
    "appId": string;
    "serial"?: string;
  };
  "root.apps.list": {
    "serial"?: string;
  };
  "root.dataAdb.backup": {
    "grant": string;
    "serial": string;
  };
  "root.dataAdb.clear": {
    "confirmationText": string;
    "serial": string;
  };
  "root.dataAdb.restore": {
    "confirmationText": string;
    "grant": string;
    "serial": string;
  };
  "root.modules.action": {
    "action": string;
    "artifactId"?: string;
    "confirmationText"?: string;
    "grant"?: string;
    "moduleId"?: string;
    "serial"?: string;
  };
  "root.modules.list": {
    "serial"?: string;
  };
  "root.modules.updates": {
    "serial"?: string;
  };
  "root.pif.document": {
    "profileId": string;
    "serial": string;
  };
  "root.pif.favorites.delete": {
    "favoriteId": string;
  };
  "root.pif.favorites.get": {
    "favoriteId": string;
  };
  "root.pif.favorites.list": Record<string, never>;
  "root.pif.favorites.save": {
    "content": string;
    "label": string;
  };
  "root.pif.inventory": {
    "serial": string;
  };
  "root.pif.transform": {
    "content": string;
    "firstApi"?: number;
    "inputFormat": string;
    "keepUnknown": boolean;
    "normalize": boolean;
    "outputFormat": string;
    "sortKeys": boolean;
  };
  "secret.issue": {
    "purpose": string;
    "secret": string;
  };
  "settings.get": Record<string, never>;
  "settings.update": {
    "automaticUpdateCheck"?: boolean;
    "checkBootloaderUnlocked"?: boolean;
    "checkDiskSpace"?: boolean;
    "checkFirmwareHash"?: boolean;
    "checkModuleUpdates"?: boolean;
    "customizeFont"?: boolean;
    "expertMode"?: boolean;
    "extraImageExtracts"?: boolean;
    "fontFace"?: string;
    "fontSize"?: number;
    "highContrast"?: boolean;
    "keepPatchTemporaryFiles"?: boolean;
    "keyboxIndex"?: boolean;
    "locale"?: string;
    "lowMemoryMode"?: boolean;
    "offerPatchMethods"?: boolean;
    "rebootTimeoutSeconds"?: number;
    "reducedMotion"?: boolean;
    "showCustomRomOptions"?: boolean;
    "showNotifications"?: boolean;
    "showRecoveryPatching"?: boolean;
    "theme"?: string;
    "toolbarPosition"?: string;
    "toolbarShowDevice"?: boolean;
    "toolbarShowLanguage"?: boolean;
    "toolbarShowTheme"?: boolean;
    "useBusyboxShell"?: boolean;
    "zoom"?: number;
  };
  "snapshot.get": Record<string, never>;
  "support.create": {
    "grant": string;
    "includeConfig"?: boolean;
    "includeLogs"?: boolean;
    "includeState"?: boolean;
    "includeSystemInfo"?: boolean;
  };
  "tools.adbShell": {
    "columns": number;
    "rows": number;
    "serial": string;
  };
  "tools.adbShell.close": {
    "sessionId": string;
  };
  "tools.adbShell.resize": {
    "columns": number;
    "rows": number;
    "sessionId": string;
  };
  "tools.adbShell.write": {
    "data": string;
    "sessionId": string;
  };
  "tools.avb": {
    "action": string;
    "currentSecurityPatch"?: string;
    "grant"?: string;
    "patchFingerprint"?: boolean;
  };
  "tools.keybox": {
    "action": string;
    "grants": string[];
  };
  "tools.logcat": {
    "buffers"?: string[];
    "filters"?: Array<{ tag: string; priority: "V" | "D" | "I" | "W" | "E" | "F" | "S" }>;
    "formatEnabled"?: boolean;
    "formatModifiers"?: string[];
    "formatVerb"?: string;
    "grant"?: string;
    "maxLines"?: number;
    "mode"?: string;
    "redaction"?: string;
    "regex"?: string;
    "serial"?: string;
    "timeoutSeconds"?: number;
    "uids"?: number[];
  };
  "tools.logcat.clear": {
    "serial"?: string;
  };
  "tools.myTools": {
    "action": string;
    "arguments"?: string[];
    "enabled"?: boolean;
    "grant"?: string;
    "title"?: string;
    "toolId"?: string;
  };
  "tools.piAnalysis": {
    "action": string;
    "serial": string;
  };
  "tools.pif": {
    "action": string;
    "baseSha256"?: string;
    "checker"?: string;
    "confirmationText": string;
    "content"?: string;
    "grant"?: string;
    "profileId"?: string;
    "serial": string;
    "targetFormat"?: string;
    "targetPackage"?: string;
  };
  "tools.pushFiles": {
    "destination": string;
    "grants": string[];
    "serial"?: string;
  };
  "tools.scrcpy": {
    "alwaysOnTop": boolean;
    "fullscreen": boolean;
    "maxFps": number;
    "maxSize": number;
    "noAudio": boolean;
    "serial"?: string;
    "showTouches": boolean;
    "stayAwake": boolean;
    "turnScreenOff": boolean;
    "videoBitRateMbps": number;
  };
  "tools.scrcpy.setup": {
    "source"?: string;
  };
  "tools.shizuku": {
    "action": string;
    "serial": string;
  };
  "tools.sos": {
    "action": string;
    "confirmationText": string;
    "serial": string;
  };
  "tools.wifi": {
    "action": string;
    "host": string;
    "port": number;
    "secretGrant"?: string;
  };
  "tools.wifi.discover": Record<string, never>;
  "tools.wifi.status": {
    "serial"?: string;
  };
  "tools.xml": {
    "action": string;
    "grant": string;
  };
  "updates.check": Record<string, never>;
}

export type BridgeCommandRequest = {
  [Command in BridgeCommand]: {
    command: Command;
    payload: BridgePayloadByCommand[Command];
  };
}[BridgeCommand];

export const allowedCommands = [
  commands.appConsoleExport,
  commands.appExit,
  commands.appOpenFolder,
  commands.appOpenLink,
  commands.appReady,
  commands.appsAction,
  commands.appsList,
  commands.backupsCreate,
  commands.backupsDelete,
  commands.backupsList,
  commands.backupsMagiskDelete,
  commands.backupsMagiskImport,
  commands.backupsMagiskList,
  commands.backupsRestore,
  commands.bootDelete,
  commands.bootFlash,
  commands.bootInventory,
  commands.bootLive,
  commands.bootPatch,
  commands.bootSelect,
  commands.deviceBootloaderLock,
  commands.deviceBootloaderUnlock,
  commands.deviceInspect,
  commands.deviceManagerPolicy,
  commands.deviceManagerRemove,
  commands.deviceManagerUpdate,
  commands.deviceOpenUrl,
  commands.deviceOtaCertificates,
  commands.deviceOtaLogs,
  commands.deviceOtaReset,
  commands.deviceOtaStatus,
  commands.deviceReboot,
  commands.deviceScan,
  commands.deviceSelect,
  commands.deviceSwitchSlot,
  commands.firmwareCatalogRefresh,
  commands.firmwareDownload,
  commands.firmwareProcess,
  commands.firmwareSelect,
  commands.flashExecute,
  commands.flashPlanPreview,
  commands.flashPlanUpdate,
  commands.interactionRespond,
  commands.nativePickDirectory,
  commands.nativePickFile,
  commands.nativePickFiles,
  commands.nativeSaveFile,
  commands.operationCancel,
  commands.partitionsErase,
  commands.partitionsList,
  commands.partitionsRead,
  commands.partitionsWrite,
  commands.platformToolsSetup,
  commands.rootAppsCatalogRefresh,
  commands.rootAppsDownload,
  commands.rootAppsInstall,
  commands.rootAppsList,
  commands.rootDataAdbBackup,
  commands.rootDataAdbClear,
  commands.rootDataAdbRestore,
  commands.rootModulesAction,
  commands.rootModulesList,
  commands.rootModulesUpdates,
  commands.rootPifDocument,
  commands.rootPifFavoritesDelete,
  commands.rootPifFavoritesGet,
  commands.rootPifFavoritesList,
  commands.rootPifFavoritesSave,
  commands.rootPifInventory,
  commands.rootPifTransform,
  commands.secretIssue,
  commands.settingsGet,
  commands.settingsUpdate,
  commands.snapshotGet,
  commands.supportCreate,
  commands.toolsAdbShell,
  commands.toolsAdbShellClose,
  commands.toolsAdbShellResize,
  commands.toolsAdbShellWrite,
  commands.toolsAvb,
  commands.toolsKeybox,
  commands.toolsLogcat,
  commands.toolsLogcatClear,
  commands.toolsMyTools,
  commands.toolsPiAnalysis,
  commands.toolsPif,
  commands.toolsPushFiles,
  commands.toolsScrcpy,
  commands.toolsScrcpySetup,
  commands.toolsShizuku,
  commands.toolsSos,
  commands.toolsWifi,
  commands.toolsWifiDiscover,
  commands.toolsWifiStatus,
  commands.toolsXml,
  commands.updatesCheck,
] as const;

export const revisionOptionalCommands = new Set<BridgeCommand>([
  commands.appReady,
  commands.settingsGet,
  commands.snapshotGet,
]);

export const commandTimeoutByName: Readonly<Record<BridgeCommand, number>> = {
  [commands.appConsoleExport]: 60000,
  [commands.appExit]: 60000,
  [commands.appOpenFolder]: 60000,
  [commands.appOpenLink]: 60000,
  [commands.appReady]: 60000,
  [commands.appsAction]: 1200000,
  [commands.appsList]: 300000,
  [commands.backupsCreate]: 1800000,
  [commands.backupsDelete]: 30000,
  [commands.backupsList]: 30000,
  [commands.backupsMagiskDelete]: 300000,
  [commands.backupsMagiskImport]: 1200000,
  [commands.backupsMagiskList]: 180000,
  [commands.backupsRestore]: 1800000,
  [commands.bootDelete]: 600000,
  [commands.bootFlash]: 1200000,
  [commands.bootInventory]: 21600000,
  [commands.bootLive]: 600000,
  [commands.bootPatch]: 10800000,
  [commands.bootSelect]: 5400000,
  [commands.deviceBootloaderLock]: 600000,
  [commands.deviceBootloaderUnlock]: 600000,
  [commands.deviceInspect]: 240000,
  [commands.deviceManagerPolicy]: 60000,
  [commands.deviceManagerRemove]: 60000,
  [commands.deviceManagerUpdate]: 60000,
  [commands.deviceOpenUrl]: 30000,
  [commands.deviceOtaCertificates]: 45000,
  [commands.deviceOtaLogs]: 180000,
  [commands.deviceOtaReset]: 120000,
  [commands.deviceOtaStatus]: 45000,
  [commands.deviceReboot]: 600000,
  [commands.deviceScan]: 600000,
  [commands.deviceSelect]: 60000,
  [commands.deviceSwitchSlot]: 600000,
  [commands.firmwareCatalogRefresh]: 300000,
  [commands.firmwareDownload]: 21600000,
  [commands.firmwareProcess]: 7200000,
  [commands.firmwareSelect]: 3600000,
  [commands.flashExecute]: 14400000,
  [commands.flashPlanPreview]: 60000,
  [commands.flashPlanUpdate]: 60000,
  [commands.interactionRespond]: 60000,
  [commands.nativePickDirectory]: 60000,
  [commands.nativePickFile]: 60000,
  [commands.nativePickFiles]: 60000,
  [commands.nativeSaveFile]: 60000,
  [commands.operationCancel]: 60000,
  [commands.partitionsErase]: 600000,
  [commands.partitionsList]: 60000,
  [commands.partitionsRead]: 1200000,
  [commands.partitionsWrite]: 1200000,
  [commands.platformToolsSetup]: 1800000,
  [commands.rootAppsCatalogRefresh]: 300000,
  [commands.rootAppsDownload]: 1800000,
  [commands.rootAppsInstall]: 1800000,
  [commands.rootAppsList]: 3600000,
  [commands.rootDataAdbBackup]: 3600000,
  [commands.rootDataAdbClear]: 600000,
  [commands.rootDataAdbRestore]: 3600000,
  [commands.rootModulesAction]: 1800000,
  [commands.rootModulesList]: 300000,
  [commands.rootModulesUpdates]: 1800000,
  [commands.rootPifDocument]: 120000,
  [commands.rootPifFavoritesDelete]: 30000,
  [commands.rootPifFavoritesGet]: 30000,
  [commands.rootPifFavoritesList]: 30000,
  [commands.rootPifFavoritesSave]: 30000,
  [commands.rootPifInventory]: 120000,
  [commands.rootPifTransform]: 30000,
  [commands.secretIssue]: 60000,
  [commands.settingsGet]: 60000,
  [commands.settingsUpdate]: 60000,
  [commands.snapshotGet]: 60000,
  [commands.supportCreate]: 1800000,
  [commands.toolsAdbShell]: 30000,
  [commands.toolsAdbShellClose]: 30000,
  [commands.toolsAdbShellResize]: 30000,
  [commands.toolsAdbShellWrite]: 30000,
  [commands.toolsAvb]: 1800000,
  [commands.toolsKeybox]: 300000,
  [commands.toolsLogcat]: 180000,
  [commands.toolsLogcatClear]: 180000,
  [commands.toolsMyTools]: 300000,
  [commands.toolsPiAnalysis]: 180000,
  [commands.toolsPif]: 120000,
  [commands.toolsPushFiles]: 21600000,
  [commands.toolsScrcpy]: 300000,
  [commands.toolsScrcpySetup]: 1800000,
  [commands.toolsShizuku]: 300000,
  [commands.toolsSos]: 300000,
  [commands.toolsWifi]: 300000,
  [commands.toolsWifiDiscover]: 20000,
  [commands.toolsWifiStatus]: 60000,
  [commands.toolsXml]: 30000,
  [commands.updatesCheck]: 60000,
};

export const bridgeCommandMetadata = {
  [commands.appConsoleExport]: {"owner":"application","mutability":"mutating","risk":"host_write","expectedRevision":"required","validDeviceStates":["*"],"planner":"native_host.console_export","confirmation":"none","postconditions":["bounded_redacted_console_exported"]},
  [commands.appExit]: {"owner":"application","mutability":"mutating","risk":"none","expectedRevision":"required","validDeviceStates":["*"],"planner":"native_host.exit","confirmation":"none","postconditions":["window_close_requested"]},
  [commands.appOpenFolder]: {"owner":"application","mutability":"read_only","risk":"host_read","expectedRevision":"required","validDeviceStates":["*"],"planner":"native_host.open_folder","confirmation":"none","postconditions":["backend_owned_directory_open_requested"]},
  [commands.appOpenLink]: {"owner":"application","mutability":"read_only","risk":"host_read","expectedRevision":"required","validDeviceStates":["*"],"planner":"native_host.open_link","confirmation":"none","postconditions":["allowlisted_https_link_open_requested"]},
  [commands.appReady]: {"owner":"application","mutability":"read_only","risk":"none","expectedRevision":"optional","validDeviceStates":["*"],"planner":"native_host.lifecycle","confirmation":"none","postconditions":["snapshot_emitted"]},
  [commands.appsAction]: {"owner":"applications","mutability":"mutating","risk":"device_write","expectedRevision":"required","validDeviceStates":["adb","recovery","sideload"],"planner":"apps.action","confirmation":"standard","postconditions":["package_state_verified"]},
  [commands.appsList]: {"owner":"applications","mutability":"read_only","risk":"device_read","expectedRevision":"required","validDeviceStates":["adb","recovery","sideload"],"planner":"apps.inventory","confirmation":"none","postconditions":["packages_returned"]},
  [commands.backupsCreate]: {"owner":"backups","mutability":"mutating","risk":"host_write","expectedRevision":"required","validDeviceStates":["adb","fastboot","fastbootd","recovery","sideload"],"planner":"backups.create","confirmation":"none","postconditions":["backup_hash_verified"]},
  [commands.backupsDelete]: {"owner":"backups","mutability":"mutating","risk":"host_write","expectedRevision":"required","validDeviceStates":["*"],"planner":"backups.delete","confirmation":"none","postconditions":["backup_record_removed"]},
  [commands.backupsList]: {"owner":"backups","mutability":"read_only","risk":"host_read","expectedRevision":"required","validDeviceStates":["*"],"planner":"backups.inventory","confirmation":"none","postconditions":["bounded_backup_inventory_returned"]},
  [commands.backupsMagiskDelete]: {"owner":"backups","mutability":"destructive","risk":"destructive","expectedRevision":"required","validDeviceStates":["adb","recovery","sideload"],"planner":"backups.magisk.delete","confirmation":"standard","postconditions":["magisk_backup_absence_verified"]},
  [commands.backupsMagiskImport]: {"owner":"backups","mutability":"mutating","risk":"device_write","expectedRevision":"required","validDeviceStates":["adb","recovery","sideload"],"planner":"backups.magisk.import","confirmation":"standard","postconditions":["magisk_backup_hash_verified"]},
  [commands.backupsMagiskList]: {"owner":"backups","mutability":"read_only","risk":"device_read","expectedRevision":"required","validDeviceStates":["adb","recovery","sideload"],"planner":"backups.magisk.list","confirmation":"none","postconditions":["bounded_magisk_backup_inventory_returned"]},
  [commands.backupsRestore]: {"owner":"backups","mutability":"mutating","risk":"device_write","expectedRevision":"required","validDeviceStates":["adb","fastboot","fastbootd","recovery","sideload"],"planner":"backups.restore","confirmation":"standard","postconditions":["restore_write_verified"]},
  [commands.bootDelete]: {"owner":"boot_images","mutability":"mutating","risk":"host_write","expectedRevision":"required","validDeviceStates":["*"],"planner":"boot_inventory.delete","confirmation":"none","postconditions":["boot_record_absent","shared_object_preserved"]},
  [commands.bootFlash]: {"owner":"boot_images","mutability":"destructive","risk":"destructive","expectedRevision":"required","validDeviceStates":["fastboot","fastbootd"],"planner":"operation.boot_flash","confirmation":"standard","postconditions":["partition_write_verified"]},
  [commands.bootInventory]: {"owner":"boot_images","mutability":"read_only","risk":"host_read","expectedRevision":"required","validDeviceStates":["*"],"planner":"boot_inventory.list","confirmation":"none","postconditions":["boot_metadata_returned"]},
  [commands.bootLive]: {"owner":"boot_images","mutability":"mutating","risk":"device_write","expectedRevision":"required","validDeviceStates":["fastboot","fastbootd"],"planner":"operation.boot_live","confirmation":"standard","postconditions":["device_reconnected","boot_completed_observed"]},
  [commands.bootPatch]: {"owner":"boot_images","mutability":"mutating","risk":"host_write","expectedRevision":"required","validDeviceStates":["adb","recovery","sideload"],"planner":"boot.patch","confirmation":"standard","postconditions":["patched_artifact_hashed","boot_repository_updated"]},
  [commands.bootSelect]: {"owner":"boot_images","mutability":"mutating","risk":"host_write","expectedRevision":"required","validDeviceStates":["*"],"planner":"boot_inventory.select","confirmation":"none","postconditions":["boot_repository_verified","boot_snapshot_matches"]},
  [commands.deviceBootloaderLock]: {"owner":"bootloader","mutability":"destructive","risk":"destructive","expectedRevision":"required","validDeviceStates":["fastboot","fastbootd"],"planner":"operation.bootloader_lock","confirmation":"lock_serial","postconditions":["bootloader_locked","relock_evidence_consumed"]},
  [commands.deviceBootloaderUnlock]: {"owner":"bootloader","mutability":"destructive","risk":"destructive","expectedRevision":"required","validDeviceStates":["fastboot","fastbootd"],"planner":"operation.bootloader_unlock","confirmation":"unlock_serial","postconditions":["bootloader_unlocked"]},
  [commands.deviceInspect]: {"owner":"device_tools","mutability":"read_only","risk":"device_read","expectedRevision":"required","validDeviceStates":["adb"],"planner":"device.inspect","confirmation":"none","postconditions":["bounded_typed_report_returned"]},
  [commands.deviceManagerPolicy]: {"owner":"device","mutability":"mutating","risk":"host_write","expectedRevision":"required","validDeviceStates":["*"],"planner":"device.manager.policy","confirmation":"none","postconditions":["scan_policy_persisted","monitor_lifecycle_matches"]},
  [commands.deviceManagerRemove]: {"owner":"device","mutability":"mutating","risk":"host_write","expectedRevision":"required","validDeviceStates":["*"],"planner":"device.manager.remove","confirmation":"none","postconditions":["managed_device_removed"]},
  [commands.deviceManagerUpdate]: {"owner":"device","mutability":"mutating","risk":"host_write","expectedRevision":"required","validDeviceStates":["*"],"planner":"device.manager.update","confirmation":"none","postconditions":["managed_device_persisted"]},
  [commands.deviceOpenUrl]: {"owner":"device_tools","mutability":"mutating","risk":"device_write","expectedRevision":"required","validDeviceStates":["adb"],"planner":"device.open_url","confirmation":"standard","postconditions":["view_intent_accepted"]},
  [commands.deviceOtaCertificates]: {"owner":"device_tools","mutability":"read_only","risk":"device_read","expectedRevision":"required","validDeviceStates":["adb"],"planner":"device.ota.certificates","confirmation":"none","postconditions":["bounded_certificate_inventory_returned"]},
  [commands.deviceOtaLogs]: {"owner":"device_tools","mutability":"read_only","risk":"device_read","expectedRevision":"required","validDeviceStates":["adb"],"planner":"device.ota.logs","confirmation":"none","postconditions":["bounded_redacted_logs_returned"]},
  [commands.deviceOtaReset]: {"owner":"device_tools","mutability":"mutating","risk":"device_write","expectedRevision":"required","validDeviceStates":["adb"],"planner":"device.ota.reset","confirmation":"standard","postconditions":["ota_idle_state"]},
  [commands.deviceOtaStatus]: {"owner":"device_tools","mutability":"read_only","risk":"device_read","expectedRevision":"required","validDeviceStates":["adb"],"planner":"device.ota.status","confirmation":"none","postconditions":["bounded_update_engine_status_returned"]},
  [commands.deviceReboot]: {"owner":"device","mutability":"mutating","risk":"device_write","expectedRevision":"required","validDeviceStates":["adb","fastboot","fastbootd","recovery","sideload"],"planner":"operation.device_reboot","confirmation":"none","postconditions":["device_reconnected","expected_mode_observed"]},
  [commands.deviceScan]: {"owner":"device","mutability":"read_only","risk":"device_read","expectedRevision":"required","validDeviceStates":["*"],"planner":"device.scan","confirmation":"none","postconditions":["device_inventory_refreshed"]},
  [commands.deviceSelect]: {"owner":"device","mutability":"mutating","risk":"none","expectedRevision":"required","validDeviceStates":["*"],"planner":"device.selection","confirmation":"none","postconditions":["selected_serials_match"]},
  [commands.deviceSwitchSlot]: {"owner":"device","mutability":"destructive","risk":"destructive","expectedRevision":"required","validDeviceStates":["fastboot","fastbootd"],"planner":"operation.slot_switch","confirmation":"slot_serial","postconditions":["active_slot_matches"]},
  [commands.firmwareCatalogRefresh]: {"owner":"firmware","mutability":"mutating","risk":"host_write","expectedRevision":"required","validDeviceStates":["*"],"planner":"firmware.catalog.refresh","confirmation":"none","postconditions":["verified_firmware_catalog_returned"]},
  [commands.firmwareDownload]: {"owner":"firmware","mutability":"mutating","risk":"host_write","expectedRevision":"required","validDeviceStates":["*"],"planner":"firmware.download","confirmation":"none","postconditions":["firmware_download_verified","firmware_snapshot_matches"]},
  [commands.firmwareProcess]: {"owner":"firmware","mutability":"mutating","risk":"host_write","expectedRevision":"required","validDeviceStates":["*"],"planner":"firmware.process","confirmation":"none","postconditions":["artifacts_hashed","firmware_repository_updated"]},
  [commands.firmwareSelect]: {"owner":"firmware","mutability":"mutating","risk":"host_read","expectedRevision":"required","validDeviceStates":["*"],"planner":"firmware.inspect","confirmation":"none","postconditions":["firmware_snapshot_matches"]},
  [commands.flashExecute]: {"owner":"flash","mutability":"destructive","risk":"destructive","expectedRevision":"required","validDeviceStates":["adb","fastboot","fastbootd","recovery","sideload"],"planner":"operation.flash","confirmation":"plan_fingerprint","postconditions":["device_reconnected","build_matches","slot_matches"]},
  [commands.flashPlanPreview]: {"owner":"flash","mutability":"read_only","risk":"device_read","expectedRevision":"required","validDeviceStates":["adb","fastboot","fastbootd","recovery","sideload"],"planner":"flash.preview","confirmation":"none","postconditions":["immutable_plan_returned"]},
  [commands.flashPlanUpdate]: {"owner":"flash","mutability":"mutating","risk":"none","expectedRevision":"required","validDeviceStates":["*"],"planner":"flash.intent","confirmation":"none","postconditions":["flash_intent_snapshot_matches"]},
  [commands.interactionRespond]: {"owner":"application","mutability":"mutating","risk":"none","expectedRevision":"required","validDeviceStates":["*"],"planner":"engine.interaction","confirmation":"none","postconditions":["interaction_acknowledged"]},
  [commands.nativePickDirectory]: {"owner":"native_host","mutability":"read_only","risk":"host_read","expectedRevision":"required","validDeviceStates":["*"],"planner":"native_host.pick_directory","confirmation":"none","postconditions":["path_grant_issued"]},
  [commands.nativePickFile]: {"owner":"native_host","mutability":"read_only","risk":"host_read","expectedRevision":"required","validDeviceStates":["*"],"planner":"native_host.pick_file","confirmation":"none","postconditions":["path_grant_issued"]},
  [commands.nativePickFiles]: {"owner":"native_host","mutability":"read_only","risk":"host_read","expectedRevision":"required","validDeviceStates":["*"],"planner":"native_host.pick_files","confirmation":"none","postconditions":["path_grants_issued"]},
  [commands.nativeSaveFile]: {"owner":"native_host","mutability":"read_only","risk":"host_write","expectedRevision":"required","validDeviceStates":["*"],"planner":"native_host.save_file","confirmation":"none","postconditions":["write_grant_issued"]},
  [commands.operationCancel]: {"owner":"application","mutability":"mutating","risk":"none","expectedRevision":"required","validDeviceStates":["*"],"planner":"engine.cancellation","confirmation":"none","postconditions":["cancellation_acknowledged"]},
  [commands.partitionsErase]: {"owner":"partitions","mutability":"destructive","risk":"destructive","expectedRevision":"required","validDeviceStates":["fastboot","fastbootd"],"planner":"partitions.erase","confirmation":"erase_partition_serial","postconditions":["partition_erased_verified"]},
  [commands.partitionsList]: {"owner":"partitions","mutability":"read_only","risk":"device_read","expectedRevision":"required","validDeviceStates":["fastboot","fastbootd"],"planner":"partitions.inventory","confirmation":"none","postconditions":["partition_inventory_returned"]},
  [commands.partitionsRead]: {"owner":"partitions","mutability":"mutating","risk":"host_write","expectedRevision":"required","validDeviceStates":["fastboot","fastbootd"],"planner":"partitions.read","confirmation":"none","postconditions":["local_hash_verified"]},
  [commands.partitionsWrite]: {"owner":"partitions","mutability":"destructive","risk":"destructive","expectedRevision":"required","validDeviceStates":["fastboot","fastbootd"],"planner":"partitions.write","confirmation":"standard","postconditions":["partition_write_verified"]},
  [commands.platformToolsSetup]: {"owner":"platform_tools","mutability":"mutating","risk":"host_write","expectedRevision":"required","validDeviceStates":["*"],"planner":"toolchain.setup","confirmation":"none","postconditions":["adb_fastboot_probed"]},
  [commands.rootAppsCatalogRefresh]: {"owner":"root","mutability":"mutating","risk":"host_write","expectedRevision":"required","validDeviceStates":["*"],"planner":"root.apps.catalog.refresh","confirmation":"none","postconditions":["verified_root_app_catalog_returned"]},
  [commands.rootAppsDownload]: {"owner":"root","mutability":"mutating","risk":"host_write","expectedRevision":"required","validDeviceStates":["*"],"planner":"root.apps.download","confirmation":"none","postconditions":["root_app_download_verified","root_app_inventory_updated"]},
  [commands.rootAppsInstall]: {"owner":"root","mutability":"mutating","risk":"device_write","expectedRevision":"required","validDeviceStates":["adb","recovery","sideload"],"planner":"root.app_install","confirmation":"standard","postconditions":["package_installed"]},
  [commands.rootAppsList]: {"owner":"root","mutability":"read_only","risk":"host_read","expectedRevision":"required","validDeviceStates":["*"],"planner":"root.apps_inventory","confirmation":"none","postconditions":["root_apps_returned"]},
  [commands.rootDataAdbBackup]: {"owner":"root","mutability":"mutating","risk":"host_write","expectedRevision":"required","validDeviceStates":["adb"],"planner":"root.data_adb.backup","confirmation":"standard","postconditions":["data_adb_backup_verified"]},
  [commands.rootDataAdbClear]: {"owner":"root","mutability":"destructive","risk":"destructive","expectedRevision":"required","validDeviceStates":["adb"],"planner":"root.data_adb.clear","confirmation":"standard","postconditions":["data_adb_empty"]},
  [commands.rootDataAdbRestore]: {"owner":"root","mutability":"destructive","risk":"destructive","expectedRevision":"required","validDeviceStates":["adb"],"planner":"root.data_adb.restore","confirmation":"standard","postconditions":["data_adb_restore_verified"]},
  [commands.rootModulesAction]: {"owner":"root","mutability":"destructive","risk":"destructive","expectedRevision":"required","validDeviceStates":["adb","recovery","sideload"],"planner":"root.module_action","confirmation":"standard","postconditions":["root_module_state_verified"]},
  [commands.rootModulesList]: {"owner":"root","mutability":"read_only","risk":"device_read","expectedRevision":"required","validDeviceStates":["adb","recovery","sideload"],"planner":"root.modules_inventory","confirmation":"none","postconditions":["root_modules_returned"]},
  [commands.rootModulesUpdates]: {"owner":"root","mutability":"mutating","risk":"host_write","expectedRevision":"required","validDeviceStates":["adb","recovery","sideload"],"planner":"root.modules_updates","confirmation":"none","postconditions":["module_update_artifacts_inspected"]},
  [commands.rootPifDocument]: {"owner":"root","mutability":"read_only","risk":"device_read","expectedRevision":"required","validDeviceStates":["adb","recovery","sideload"],"planner":"root.pif.document","confirmation":"none","postconditions":["bounded_pif_document_returned"]},
  [commands.rootPifFavoritesDelete]: {"owner":"root","mutability":"mutating","risk":"host_write","expectedRevision":"required","validDeviceStates":["*"],"planner":"root.pif.favorites.delete","confirmation":"none","postconditions":["pif_favorite_deleted"]},
  [commands.rootPifFavoritesGet]: {"owner":"root","mutability":"read_only","risk":"none","expectedRevision":"required","validDeviceStates":["*"],"planner":"root.pif.favorites.get","confirmation":"none","postconditions":["bounded_pif_favorite_returned"]},
  [commands.rootPifFavoritesList]: {"owner":"root","mutability":"read_only","risk":"none","expectedRevision":"required","validDeviceStates":["*"],"planner":"root.pif.favorites.list","confirmation":"none","postconditions":["bounded_pif_favorites_returned"]},
  [commands.rootPifFavoritesSave]: {"owner":"root","mutability":"mutating","risk":"host_write","expectedRevision":"required","validDeviceStates":["*"],"planner":"root.pif.favorites.save","confirmation":"none","postconditions":["pif_favorite_persisted"]},
  [commands.rootPifInventory]: {"owner":"root","mutability":"read_only","risk":"device_read","expectedRevision":"required","validDeviceStates":["adb","recovery","sideload"],"planner":"root.pif.inventory","confirmation":"none","postconditions":["bounded_pif_inventory_returned"]},
  [commands.rootPifTransform]: {"owner":"root","mutability":"read_only","risk":"none","expectedRevision":"required","validDeviceStates":["*"],"planner":"root.pif.transform","confirmation":"none","postconditions":["bounded_pif_transformation_returned"]},
  [commands.secretIssue]: {"owner":"native_host","mutability":"mutating","risk":"none","expectedRevision":"required","validDeviceStates":["*"],"planner":"native_host.secret_grant","confirmation":"none","postconditions":["secret_grant_issued"]},
  [commands.settingsGet]: {"owner":"settings","mutability":"read_only","risk":"host_read","expectedRevision":"optional","validDeviceStates":["*"],"planner":"runtime.settings_get","confirmation":"none","postconditions":["preferences_returned"]},
  [commands.settingsUpdate]: {"owner":"settings","mutability":"mutating","risk":"host_write","expectedRevision":"required","validDeviceStates":["*"],"planner":"runtime.settings_update","confirmation":"none","postconditions":["preferences_persisted"]},
  [commands.snapshotGet]: {"owner":"application","mutability":"read_only","risk":"none","expectedRevision":"optional","validDeviceStates":["*"],"planner":"engine.snapshot","confirmation":"none","postconditions":["snapshot_returned"]},
  [commands.supportCreate]: {"owner":"support","mutability":"mutating","risk":"host_write","expectedRevision":"required","validDeviceStates":["*"],"planner":"support.package_v2","confirmation":"none","postconditions":["encrypted_container_verified"]},
  [commands.toolsAdbShell]: {"owner":"device_tools","mutability":"mutating","risk":"device_write","expectedRevision":"required","validDeviceStates":["adb"],"planner":"native_host.adb_terminal.open","confirmation":"none","postconditions":["pty_bound_to_serial_revision_and_adb_state"]},
  [commands.toolsAdbShellClose]: {"owner":"device_tools","mutability":"mutating","risk":"none","expectedRevision":"required","validDeviceStates":["*"],"planner":"native_host.adb_terminal.close","confirmation":"none","postconditions":["pty_session_closed"]},
  [commands.toolsAdbShellResize]: {"owner":"device_tools","mutability":"mutating","risk":"none","expectedRevision":"required","validDeviceStates":["adb"],"planner":"native_host.adb_terminal.resize","confirmation":"none","postconditions":["pty_size_updated_for_bound_session"]},
  [commands.toolsAdbShellWrite]: {"owner":"device_tools","mutability":"mutating","risk":"device_write","expectedRevision":"required","validDeviceStates":["adb"],"planner":"native_host.adb_terminal.write","confirmation":"none","postconditions":["pty_input_accepted_for_bound_session"]},
  [commands.toolsAvb]: {"owner":"developer_tools","mutability":"mutating","risk":"host_write","expectedRevision":"required","validDeviceStates":["*"],"planner":"avb_downgrade.patch_service","confirmation":"none","postconditions":["downgrade_artifact_registered"]},
  [commands.toolsKeybox]: {"owner":"developer_tools","mutability":"read_only","risk":"host_read","expectedRevision":"required","validDeviceStates":["*"],"planner":"keybox.analyze","confirmation":"none","postconditions":["bounded_keybox_reports_returned"]},
  [commands.toolsLogcat]: {"owner":"device_tools","mutability":"mutating","risk":"host_write","expectedRevision":"required","validDeviceStates":["adb"],"planner":"tools.logcat","confirmation":"none","postconditions":["bounded_log_returned"]},
  [commands.toolsLogcatClear]: {"owner":"device_tools","mutability":"destructive","risk":"destructive","expectedRevision":"required","validDeviceStates":["adb"],"planner":"tools.logcat.clear","confirmation":"standard","postconditions":["logcat_buffers_cleared"]},
  [commands.toolsMyTools]: {"owner":"developer_tools","mutability":"mutating","risk":"host_write","expectedRevision":"required","validDeviceStates":["*"],"planner":"my_tools.safe_argv","confirmation":"none","postconditions":["profile_persisted_or_process_exit_zero"]},
  [commands.toolsPiAnalysis]: {"owner":"root","mutability":"read_only","risk":"device_read","expectedRevision":"required","validDeviceStates":["adb"],"planner":"root.pi_analysis","confirmation":"none","postconditions":["bounded_redacted_analysis_returned"]},
  [commands.toolsPif]: {"owner":"root","mutability":"destructive","risk":"destructive","expectedRevision":"required","validDeviceStates":["adb","recovery","sideload"],"planner":"root.pif.action","confirmation":"standard","postconditions":["pif_or_target_state_verified"]},
  [commands.toolsPushFiles]: {"owner":"device_tools","mutability":"mutating","risk":"device_write","expectedRevision":"required","validDeviceStates":["adb"],"planner":"tools.push_files","confirmation":"standard","postconditions":["remote_files_written"]},
  [commands.toolsScrcpy]: {"owner":"device_tools","mutability":"read_only","risk":"device_read","expectedRevision":"required","validDeviceStates":["adb"],"planner":"tools.scrcpy","confirmation":"none","postconditions":["managed_process_started"]},
  [commands.toolsScrcpySetup]: {"owner":"device_tools","mutability":"mutating","risk":"host_write","expectedRevision":"required","validDeviceStates":["*"],"planner":"tools.scrcpy.setup","confirmation":"none","postconditions":["scrcpy_binary_probed"]},
  [commands.toolsShizuku]: {"owner":"root","mutability":"mutating","risk":"device_write","expectedRevision":"required","validDeviceStates":["adb"],"planner":"root.recovery.shizuku","confirmation":"standard","postconditions":["shizuku_process_running"]},
  [commands.toolsSos]: {"owner":"root","mutability":"mutating","risk":"device_write","expectedRevision":"required","validDeviceStates":["adb"],"planner":"root.recovery.sos","confirmation":"standard","postconditions":["all_magisk_modules_disabled"]},
  [commands.toolsWifi]: {"owner":"device_tools","mutability":"mutating","risk":"host_write","expectedRevision":"required","validDeviceStates":["*"],"planner":"tools.wifi","confirmation":"none","postconditions":["adb_endpoint_observed"]},
  [commands.toolsWifiDiscover]: {"owner":"device_tools","mutability":"read_only","risk":"host_read","expectedRevision":"required","validDeviceStates":["*"],"planner":"tools.wifi.discover","confirmation":"none","postconditions":[]},
  [commands.toolsWifiStatus]: {"owner":"device_tools","mutability":"read_only","risk":"device_read","expectedRevision":"required","validDeviceStates":["adb"],"planner":"tools.wifi.status","confirmation":"none","postconditions":["adb_device_state_returned"]},
  [commands.toolsXml]: {"owner":"developer_tools","mutability":"read_only","risk":"host_read","expectedRevision":"required","validDeviceStates":["*"],"planner":"binary_xml.decode","confirmation":"none","postconditions":["bounded_xml_returned"]},
  [commands.updatesCheck]: {"owner":"support","mutability":"read_only","risk":"host_read","expectedRevision":"required","validDeviceStates":["*"],"planner":"runtime.update_check","confirmation":"none","postconditions":["signed_manifest_authenticated","rollback_sequence_persisted"]},
} as const satisfies Readonly<Record<BridgeCommand, {
  owner: string;
  mutability: string;
  risk: string;
  expectedRevision: 'optional' | 'required';
  validDeviceStates: readonly string[];
  planner: string;
  confirmation: string;
  postconditions: readonly string[];
}>>;

type GeneratedPayloadKind =
  | 'string'
  | 'boolean'
  | 'integer'
  | 'number'
  | 'object'
  | 'array'
  | 'string_array'
  | 'integer_array'
  | 'logcat_filter_array'
  | 'filter_array';

interface GeneratedPayloadField {
  readonly kind: GeneratedPayloadKind;
  readonly required: boolean;
  readonly minItems?: number;
  readonly maxItems?: number;
}

export const bridgePayloadSchemas: Readonly<Record<
  BridgeCommand,
  Readonly<Record<string, GeneratedPayloadField>>
>> = {
  [commands.appConsoleExport]: {"grant":{"kind":"string","required":true},"lines":{"kind":"string_array","required":true,"minItems":1,"maxItems":200}},
  [commands.appExit]: {},
  [commands.appOpenFolder]: {"target":{"kind":"string","required":true}},
  [commands.appOpenLink]: {"target":{"kind":"string","required":true}},
  [commands.appReady]: {},
  [commands.appsAction]: {"action":{"kind":"string","required":true},"grant":{"kind":"string","required":false},"options":{"kind":"object","required":false},"package":{"kind":"string","required":false},"packages":{"kind":"string_array","required":false},"scope":{"kind":"string","required":false},"serial":{"kind":"string","required":false}},
  [commands.appsList]: {"scope":{"kind":"string","required":false},"serial":{"kind":"string","required":false}},
  [commands.backupsCreate]: {"grant":{"kind":"string","required":true},"partition":{"kind":"string","required":true},"serial":{"kind":"string","required":false},"slot":{"kind":"string","required":true}},
  [commands.backupsDelete]: {"backupId":{"kind":"string","required":true},"confirmationText":{"kind":"string","required":true}},
  [commands.backupsList]: {"serial":{"kind":"string","required":false}},
  [commands.backupsMagiskDelete]: {"confirmationText":{"kind":"string","required":true},"serial":{"kind":"string","required":true},"sha1":{"kind":"string","required":true}},
  [commands.backupsMagiskImport]: {"grant":{"kind":"string","required":true},"serial":{"kind":"string","required":true}},
  [commands.backupsMagiskList]: {"serial":{"kind":"string","required":true}},
  [commands.backupsRestore]: {"backupId":{"kind":"string","required":false},"grant":{"kind":"string","required":false},"partition":{"kind":"string","required":true},"serial":{"kind":"string","required":false},"slot":{"kind":"string","required":true}},
  [commands.bootDelete]: {"bootId":{"kind":"string","required":true}},
  [commands.bootFlash]: {"confirmationText":{"kind":"string","required":false},"partition":{"kind":"string","required":false},"serial":{"kind":"string","required":false},"slot":{"kind":"string","required":false}},
  [commands.bootInventory]: {},
  [commands.bootLive]: {"confirmationText":{"kind":"string","required":false},"serial":{"kind":"string","required":false}},
  [commands.bootPatch]: {"appId":{"kind":"string","required":true},"flavor":{"kind":"string","required":false},"grant":{"kind":"string","required":true},"method":{"kind":"string","required":false},"secretGrant":{"kind":"string","required":false},"serial":{"kind":"string","required":false}},
  [commands.bootSelect]: {"bootId":{"kind":"string","required":false},"grant":{"kind":"string","required":false},"partition":{"kind":"string","required":false}},
  [commands.deviceBootloaderLock]: {"confirmationText":{"kind":"string","required":false},"serial":{"kind":"string","required":false}},
  [commands.deviceBootloaderUnlock]: {"confirmationText":{"kind":"string","required":false},"serial":{"kind":"string","required":false}},
  [commands.deviceInspect]: {"action":{"kind":"string","required":true},"serial":{"kind":"string","required":false}},
  [commands.deviceManagerPolicy]: {"scanEnabled":{"kind":"boolean","required":false},"scanScope":{"kind":"string","required":false}},
  [commands.deviceManagerRemove]: {"serial":{"kind":"string","required":true}},
  [commands.deviceManagerUpdate]: {"enabled":{"kind":"boolean","required":false},"label":{"kind":"string","required":false},"serial":{"kind":"string","required":true}},
  [commands.deviceOpenUrl]: {"serial":{"kind":"string","required":false},"url":{"kind":"string","required":true}},
  [commands.deviceOtaCertificates]: {"serial":{"kind":"string","required":false}},
  [commands.deviceOtaLogs]: {"maxLines":{"kind":"integer","required":false},"serial":{"kind":"string","required":false},"timeoutSeconds":{"kind":"integer","required":false}},
  [commands.deviceOtaReset]: {"serial":{"kind":"string","required":false}},
  [commands.deviceOtaStatus]: {"serial":{"kind":"string","required":false}},
  [commands.deviceReboot]: {"mode":{"kind":"string","required":false},"serial":{"kind":"string","required":false}},
  [commands.deviceScan]: {"includeBattery":{"kind":"boolean","required":false},"includeProperties":{"kind":"boolean","required":false}},
  [commands.deviceSelect]: {"serials":{"kind":"string_array","required":true}},
  [commands.deviceSwitchSlot]: {"confirmationText":{"kind":"string","required":false},"serial":{"kind":"string","required":false},"slot":{"kind":"string","required":true}},
  [commands.firmwareCatalogRefresh]: {"channel":{"kind":"string","required":false},"device":{"kind":"string","required":false}},
  [commands.firmwareDownload]: {"artifactId":{"kind":"string","required":true}},
  [commands.firmwareProcess]: {},
  [commands.firmwareSelect]: {"expectedKind":{"kind":"string","required":false},"firmwareId":{"kind":"string","required":false},"grant":{"kind":"string","required":false}},
  [commands.flashExecute]: {"confirmationText":{"kind":"string","required":false},"serial":{"kind":"string","required":false}},
  [commands.flashPlanPreview]: {"serial":{"kind":"string","required":false}},
  [commands.flashPlanUpdate]: {"dryRun":{"kind":"boolean","required":false},"mode":{"kind":"string","required":false},"options":{"kind":"object","required":false}},
  [commands.interactionRespond]: {"decision":{"kind":"string","required":true},"operationId":{"kind":"string","required":true}},
  [commands.nativePickDirectory]: {"purpose":{"kind":"string","required":true},"title":{"kind":"string","required":false}},
  [commands.nativePickFile]: {"filters":{"kind":"filter_array","required":false},"purpose":{"kind":"string","required":true},"title":{"kind":"string","required":false}},
  [commands.nativePickFiles]: {"filters":{"kind":"filter_array","required":false},"purpose":{"kind":"string","required":true},"title":{"kind":"string","required":false}},
  [commands.nativeSaveFile]: {"defaultName":{"kind":"string","required":false},"filters":{"kind":"filter_array","required":false},"purpose":{"kind":"string","required":true},"title":{"kind":"string","required":false}},
  [commands.operationCancel]: {"operationId":{"kind":"string","required":true}},
  [commands.partitionsErase]: {"confirmationText":{"kind":"string","required":false},"partition":{"kind":"string","required":true},"serial":{"kind":"string","required":false}},
  [commands.partitionsList]: {"serial":{"kind":"string","required":false}},
  [commands.partitionsRead]: {"grant":{"kind":"string","required":true},"overwrite":{"kind":"boolean","required":false},"partition":{"kind":"string","required":true},"serial":{"kind":"string","required":false}},
  [commands.partitionsWrite]: {"grant":{"kind":"string","required":true},"partition":{"kind":"string","required":true},"serial":{"kind":"string","required":false}},
  [commands.platformToolsSetup]: {"grant":{"kind":"string","required":false},"source":{"kind":"string","required":true}},
  [commands.rootAppsCatalogRefresh]: {"channel":{"kind":"string","required":false}},
  [commands.rootAppsDownload]: {"artifactId":{"kind":"string","required":true}},
  [commands.rootAppsInstall]: {"appId":{"kind":"string","required":true},"serial":{"kind":"string","required":false}},
  [commands.rootAppsList]: {"serial":{"kind":"string","required":false}},
  [commands.rootDataAdbBackup]: {"grant":{"kind":"string","required":true},"serial":{"kind":"string","required":true}},
  [commands.rootDataAdbClear]: {"confirmationText":{"kind":"string","required":true},"serial":{"kind":"string","required":true}},
  [commands.rootDataAdbRestore]: {"confirmationText":{"kind":"string","required":true},"grant":{"kind":"string","required":true},"serial":{"kind":"string","required":true}},
  [commands.rootModulesAction]: {"action":{"kind":"string","required":true},"artifactId":{"kind":"string","required":false},"confirmationText":{"kind":"string","required":false},"grant":{"kind":"string","required":false},"moduleId":{"kind":"string","required":false},"serial":{"kind":"string","required":false}},
  [commands.rootModulesList]: {"serial":{"kind":"string","required":false}},
  [commands.rootModulesUpdates]: {"serial":{"kind":"string","required":false}},
  [commands.rootPifDocument]: {"profileId":{"kind":"string","required":true},"serial":{"kind":"string","required":true}},
  [commands.rootPifFavoritesDelete]: {"favoriteId":{"kind":"string","required":true}},
  [commands.rootPifFavoritesGet]: {"favoriteId":{"kind":"string","required":true}},
  [commands.rootPifFavoritesList]: {},
  [commands.rootPifFavoritesSave]: {"content":{"kind":"string","required":true},"label":{"kind":"string","required":true}},
  [commands.rootPifInventory]: {"serial":{"kind":"string","required":true}},
  [commands.rootPifTransform]: {"content":{"kind":"string","required":true},"firstApi":{"kind":"integer","required":false},"inputFormat":{"kind":"string","required":true},"keepUnknown":{"kind":"boolean","required":true},"normalize":{"kind":"boolean","required":true},"outputFormat":{"kind":"string","required":true},"sortKeys":{"kind":"boolean","required":true}},
  [commands.secretIssue]: {"purpose":{"kind":"string","required":true},"secret":{"kind":"string","required":true}},
  [commands.settingsGet]: {},
  [commands.settingsUpdate]: {"automaticUpdateCheck":{"kind":"boolean","required":false},"checkBootloaderUnlocked":{"kind":"boolean","required":false},"checkDiskSpace":{"kind":"boolean","required":false},"checkFirmwareHash":{"kind":"boolean","required":false},"checkModuleUpdates":{"kind":"boolean","required":false},"customizeFont":{"kind":"boolean","required":false},"expertMode":{"kind":"boolean","required":false},"extraImageExtracts":{"kind":"boolean","required":false},"fontFace":{"kind":"string","required":false},"fontSize":{"kind":"integer","required":false},"highContrast":{"kind":"boolean","required":false},"keepPatchTemporaryFiles":{"kind":"boolean","required":false},"keyboxIndex":{"kind":"boolean","required":false},"locale":{"kind":"string","required":false},"lowMemoryMode":{"kind":"boolean","required":false},"offerPatchMethods":{"kind":"boolean","required":false},"rebootTimeoutSeconds":{"kind":"integer","required":false},"reducedMotion":{"kind":"boolean","required":false},"showCustomRomOptions":{"kind":"boolean","required":false},"showNotifications":{"kind":"boolean","required":false},"showRecoveryPatching":{"kind":"boolean","required":false},"theme":{"kind":"string","required":false},"toolbarPosition":{"kind":"string","required":false},"toolbarShowDevice":{"kind":"boolean","required":false},"toolbarShowLanguage":{"kind":"boolean","required":false},"toolbarShowTheme":{"kind":"boolean","required":false},"useBusyboxShell":{"kind":"boolean","required":false},"zoom":{"kind":"integer","required":false}},
  [commands.snapshotGet]: {},
  [commands.supportCreate]: {"grant":{"kind":"string","required":true},"includeConfig":{"kind":"boolean","required":false},"includeLogs":{"kind":"boolean","required":false},"includeState":{"kind":"boolean","required":false},"includeSystemInfo":{"kind":"boolean","required":false}},
  [commands.toolsAdbShell]: {"columns":{"kind":"integer","required":true},"rows":{"kind":"integer","required":true},"serial":{"kind":"string","required":true}},
  [commands.toolsAdbShellClose]: {"sessionId":{"kind":"string","required":true}},
  [commands.toolsAdbShellResize]: {"columns":{"kind":"integer","required":true},"rows":{"kind":"integer","required":true},"sessionId":{"kind":"string","required":true}},
  [commands.toolsAdbShellWrite]: {"data":{"kind":"string","required":true},"sessionId":{"kind":"string","required":true}},
  [commands.toolsAvb]: {"action":{"kind":"string","required":true},"currentSecurityPatch":{"kind":"string","required":false},"grant":{"kind":"string","required":false},"patchFingerprint":{"kind":"boolean","required":false}},
  [commands.toolsKeybox]: {"action":{"kind":"string","required":true},"grants":{"kind":"string_array","required":true,"minItems":1,"maxItems":32}},
  [commands.toolsLogcat]: {"buffers":{"kind":"string_array","required":false,"minItems":1,"maxItems":6},"filters":{"kind":"logcat_filter_array","required":false,"minItems":0,"maxItems":32},"formatEnabled":{"kind":"boolean","required":false},"formatModifiers":{"kind":"string_array","required":false,"minItems":0,"maxItems":7},"formatVerb":{"kind":"string","required":false},"grant":{"kind":"string","required":false},"maxLines":{"kind":"integer","required":false},"mode":{"kind":"string","required":false},"redaction":{"kind":"string","required":false},"regex":{"kind":"string","required":false},"serial":{"kind":"string","required":false},"timeoutSeconds":{"kind":"integer","required":false},"uids":{"kind":"integer_array","required":false,"minItems":0,"maxItems":32}},
  [commands.toolsLogcatClear]: {"serial":{"kind":"string","required":false}},
  [commands.toolsMyTools]: {"action":{"kind":"string","required":true},"arguments":{"kind":"string_array","required":false,"minItems":0,"maxItems":128},"enabled":{"kind":"boolean","required":false},"grant":{"kind":"string","required":false},"title":{"kind":"string","required":false},"toolId":{"kind":"string","required":false}},
  [commands.toolsPiAnalysis]: {"action":{"kind":"string","required":true},"serial":{"kind":"string","required":true}},
  [commands.toolsPif]: {"action":{"kind":"string","required":true},"baseSha256":{"kind":"string","required":false},"checker":{"kind":"string","required":false},"confirmationText":{"kind":"string","required":true},"content":{"kind":"string","required":false},"grant":{"kind":"string","required":false},"profileId":{"kind":"string","required":false},"serial":{"kind":"string","required":true},"targetFormat":{"kind":"string","required":false},"targetPackage":{"kind":"string","required":false}},
  [commands.toolsPushFiles]: {"destination":{"kind":"string","required":true},"grants":{"kind":"string_array","required":true,"minItems":1,"maxItems":32},"serial":{"kind":"string","required":false}},
  [commands.toolsScrcpy]: {"alwaysOnTop":{"kind":"boolean","required":true},"fullscreen":{"kind":"boolean","required":true},"maxFps":{"kind":"integer","required":true},"maxSize":{"kind":"integer","required":true},"noAudio":{"kind":"boolean","required":true},"serial":{"kind":"string","required":false},"showTouches":{"kind":"boolean","required":true},"stayAwake":{"kind":"boolean","required":true},"turnScreenOff":{"kind":"boolean","required":true},"videoBitRateMbps":{"kind":"integer","required":true}},
  [commands.toolsScrcpySetup]: {"source":{"kind":"string","required":false}},
  [commands.toolsShizuku]: {"action":{"kind":"string","required":true},"serial":{"kind":"string","required":true}},
  [commands.toolsSos]: {"action":{"kind":"string","required":true},"confirmationText":{"kind":"string","required":true},"serial":{"kind":"string","required":true}},
  [commands.toolsWifi]: {"action":{"kind":"string","required":true},"host":{"kind":"string","required":true},"port":{"kind":"integer","required":true},"secretGrant":{"kind":"string","required":false}},
  [commands.toolsWifiDiscover]: {},
  [commands.toolsWifiStatus]: {"serial":{"kind":"string","required":false}},
  [commands.toolsXml]: {"action":{"kind":"string","required":true},"grant":{"kind":"string","required":true}},
  [commands.updatesCheck]: {},
};

const commandSet = new Set<string>(allowedCommands);

export function isBridgeCommand(value: unknown): value is BridgeCommand {
  return typeof value === 'string' && commandSet.has(value);
}

function matchesPayloadKind(value: unknown, kind: GeneratedPayloadKind): boolean {
  switch (kind) {
    case 'string': return typeof value === 'string';
    case 'boolean': return typeof value === 'boolean';
    case 'integer': return typeof value === 'number' && Number.isInteger(value);
    case 'number': return typeof value === 'number' && Number.isFinite(value);
    case 'object': return value !== null && typeof value === 'object' && !Array.isArray(value);
    case 'array': return Array.isArray(value);
    case 'integer_array': return Array.isArray(value) && value.every((item) => Number.isSafeInteger(item));
    case 'logcat_filter_array': return Array.isArray(value) && value.every((item) => {
      if (item === null || typeof item !== 'object' || Array.isArray(item)) return false;
      const filter = item as Record<string, unknown>;
      const keys = Object.keys(filter).sort();
      return keys.length === 2 && keys[0] === 'priority' && keys[1] === 'tag'
        && typeof filter.tag === 'string' && typeof filter.priority === 'string';
    });
    case 'filter_array': return Array.isArray(value) && value.every((item) => {
      if (item === null || typeof item !== 'object' || Array.isArray(item)) return false;
      const filter = item as Record<string, unknown>;
      if (Object.keys(filter).length !== 2 || typeof filter.label !== 'string') return false;
      return Array.isArray(filter.extensions) && filter.extensions.every((entry) => typeof entry === 'string');
    });
    case 'string_array': return Array.isArray(value) && value.every((item) => typeof item === 'string');
  }
}

export function isBridgePayload<Command extends BridgeCommand>(
  command: Command,
  payload: unknown,
): payload is BridgePayloadByCommand[Command] {
  if (payload === null || typeof payload !== 'object' || Array.isArray(payload)) return false;
  const schema = bridgePayloadSchemas[command];
  const values = payload as Record<string, unknown>;
  for (const key of Object.keys(values)) {
    if (!Object.prototype.hasOwnProperty.call(schema, key)) return false;
  }
  for (const [key, field] of Object.entries(schema)) {
    if (!Object.prototype.hasOwnProperty.call(values, key)) {
      if (field.required) return false;
      continue;
    }
    if (!matchesPayloadKind(values[key], field.kind)) return false;
    if (Array.isArray(values[key]) && field.minItems !== undefined && (
      values[key].length < field.minItems
      || values[key].length > (field.maxItems ?? field.minItems)
    )) return false;
  }
  return true;
}
