#!/usr/bin/env python3
"""Generate/check the React WebView v2 contract from the Python registry."""

from __future__ import annotations

import argparse
import json
import sys
from collections.abc import Sequence
from pathlib import Path

_REPOSITORY_ROOT = Path(__file__).resolve().parent.parent
if str(_REPOSITORY_ROOT) not in sys.path:
    sys.path.insert(0, str(_REPOSITORY_ROOT))

from ui.command_registry import (  # noqa: E402
    ALLOWED_COMMANDS,
    BRIDGE_VERSION,
    COMMAND_REGISTRY,
    ExpectedRevision,
    PayloadKind,
)

DEFAULT_OUTPUT = _REPOSITORY_ROOT / "ui" / "web" / "src" / "commands.ts"

_TYPESCRIPT_TYPES = {
    PayloadKind.STRING: "string",
    PayloadKind.BOOLEAN: "boolean",
    PayloadKind.INTEGER: "number",
    PayloadKind.NUMBER: "number",
    PayloadKind.OBJECT: "Record<string, unknown>",
    PayloadKind.ARRAY: "unknown[]",
    PayloadKind.STRING_ARRAY: "string[]",
    PayloadKind.FILTER_ARRAY: "Array<{ label: string; extensions: string[] }>",
}


def _json(value: object) -> str:
    return json.dumps(value, ensure_ascii=False, separators=(",", ":"))


def render_typescript() -> str:
    specs = [COMMAND_REGISTRY[command] for command in sorted(ALLOWED_COMMANDS)]
    lines = [
        "// @generated by scripts/generate_bridge_contracts.py; DO NOT EDIT.",
        "// Python ui.command_registry.COMMAND_REGISTRY is the canonical source.",
        "",
        f"export const bridgeVersion = {BRIDGE_VERSION} as const;",
        "",
        "export const commands = {",
    ]
    lines.extend(
        f"  {spec.typescript_name}: {_json(spec.command)}," for spec in specs
    )
    lines.extend(
        [
            "} as const;",
            "",
            "export type BridgeCommand = (typeof commands)[keyof typeof commands];",
            "",
            "export interface BridgePayloadByCommand {",
        ]
    )
    for spec in specs:
        fields = spec.payload.fields
        if not fields:
            lines.append(f"  {_json(spec.command)}: Record<string, never>;")
            continue
        lines.append(f"  {_json(spec.command)}: {{")
        for name, field in fields.items():
            marker = "" if field.required else "?"
            lines.append(
                f"    {_json(name)}{marker}: {_TYPESCRIPT_TYPES[field.kind]};"
            )
        lines.append("  };")
    lines.extend(
        [
            "}",
            "",
            "export type BridgeCommandRequest = {",
            "  [Command in BridgeCommand]: {",
            "    command: Command;",
            "    payload: BridgePayloadByCommand[Command];",
            "  };",
            "}[BridgeCommand];",
            "",
            "export const allowedCommands = [",
        ]
    )
    lines.extend(f"  commands.{spec.typescript_name}," for spec in specs)
    lines.extend(
        [
            "] as const;",
            "",
            "export const revisionOptionalCommands = new Set<BridgeCommand>([",
        ]
    )
    lines.extend(
        f"  commands.{spec.typescript_name},"
        for spec in specs
        if spec.expected_revision is ExpectedRevision.OPTIONAL
    )
    lines.extend(
        [
            "]);",
            "",
            "export const commandTimeoutByName: Readonly<Record<BridgeCommand, number>> = {",
        ]
    )
    lines.extend(
        f"  [commands.{spec.typescript_name}]: {spec.timeout_ms}," for spec in specs
    )
    lines.extend(
        [
            "};",
            "",
            "export const bridgeCommandMetadata = {",
        ]
    )
    for spec in specs:
        metadata = {
            "owner": spec.owner.value,
            "mutability": spec.mutability.value,
            "risk": spec.risk.value,
            "expectedRevision": spec.expected_revision.value,
            "validDeviceStates": sorted(spec.valid_device_states),
            "planner": spec.planner,
            "confirmation": spec.confirmation.value,
            "postconditions": list(spec.postconditions),
        }
        lines.append(
            f"  [commands.{spec.typescript_name}]: {_json(metadata)},"
        )
    lines.extend(
        [
            "} as const satisfies Readonly<Record<BridgeCommand, {",
            "  owner: string;",
            "  mutability: string;",
            "  risk: string;",
            "  expectedRevision: 'optional' | 'required';",
            "  validDeviceStates: readonly string[];",
            "  planner: string;",
            "  confirmation: string;",
            "  postconditions: readonly string[];",
            "}>>;",
            "",
            "type GeneratedPayloadKind =",
            "  | 'string'",
            "  | 'boolean'",
            "  | 'integer'",
            "  | 'number'",
            "  | 'object'",
            "  | 'array'",
            "  | 'string_array'",
            "  | 'filter_array';",
            "",
            "interface GeneratedPayloadField {",
            "  readonly kind: GeneratedPayloadKind;",
            "  readonly required: boolean;",
            "}",
            "",
            "export const bridgePayloadSchemas: Readonly<Record<",
            "  BridgeCommand,",
            "  Readonly<Record<string, GeneratedPayloadField>>",
            ">> = {",
        ]
    )
    for spec in specs:
        fields = {
            name: {"kind": field.kind.value, "required": field.required}
            for name, field in spec.payload.fields.items()
        }
        lines.append(f"  [commands.{spec.typescript_name}]: {_json(fields)},")
    lines.extend(
        [
            "};",
            "",
            "const commandSet = new Set<string>(allowedCommands);",
            "",
            "export function isBridgeCommand(value: unknown): value is BridgeCommand {",
            "  return typeof value === 'string' && commandSet.has(value);",
            "}",
            "",
            "function matchesPayloadKind(value: unknown, kind: GeneratedPayloadKind): boolean {",
            "  switch (kind) {",
            "    case 'string': return typeof value === 'string';",
            "    case 'boolean': return typeof value === 'boolean';",
            "    case 'integer': return typeof value === 'number' && Number.isInteger(value);",
            "    case 'number': return typeof value === 'number' && Number.isFinite(value);",
            "    case 'object': return value !== null && typeof value === 'object' && !Array.isArray(value);",
            "    case 'array': return Array.isArray(value);",
            "    case 'filter_array': return Array.isArray(value) && value.every((item) => {",
            "      if (item === null || typeof item !== 'object' || Array.isArray(item)) return false;",
            "      const filter = item as Record<string, unknown>;",
            "      if (Object.keys(filter).length !== 2 || typeof filter.label !== 'string') return false;",
            "      return Array.isArray(filter.extensions) && filter.extensions.every((entry) => typeof entry === 'string');",
            "    });",
            "    case 'string_array': return Array.isArray(value) && value.every((item) => typeof item === 'string');",
            "  }",
            "}",
            "",
            "export function isBridgePayload<Command extends BridgeCommand>(",
            "  command: Command,",
            "  payload: unknown,",
            "): payload is BridgePayloadByCommand[Command] {",
            "  if (payload === null || typeof payload !== 'object' || Array.isArray(payload)) return false;",
            "  const schema = bridgePayloadSchemas[command];",
            "  const values = payload as Record<string, unknown>;",
            "  for (const key of Object.keys(values)) {",
            "    if (!Object.prototype.hasOwnProperty.call(schema, key)) return false;",
            "  }",
            "  for (const [key, field] of Object.entries(schema)) {",
            "    if (!Object.prototype.hasOwnProperty.call(values, key)) {",
            "      if (field.required) return false;",
            "      continue;",
            "    }",
            "    if (!matchesPayloadKind(values[key], field.kind)) return false;",
            "  }",
            "  return true;",
            "}",
            "",
        ]
    )
    return "\n".join(lines)


def write_or_check(path: Path, *, check: bool) -> bool:
    expected = render_typescript()
    if check:
        try:
            actual = path.read_text(encoding="utf-8")
        except FileNotFoundError:
            return False
        return actual == expected
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(expected, encoding="utf-8", newline="\n")
    return True


def _parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--output", type=Path, default=DEFAULT_OUTPUT)
    parser.add_argument("--check", action="store_true")
    return parser


def main(argv: Sequence[str] | None = None) -> int:
    args = _parser().parse_args(argv)
    if write_or_check(args.output, check=args.check):
        action = "Verified" if args.check else "Generated"
        print(f"{action} {args.output}")
        return 0
    print(
        f"error: {args.output} is stale; run scripts/generate_bridge_contracts.py",
        file=sys.stderr,
    )
    return 1


if __name__ == "__main__":
    raise SystemExit(main())
